# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # job 1: only viam_sdk, use widen
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "viam_sdk"
    versioning-strategy: widen
    
  # job 2: all other pub deps, default behavior
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "viam_sdk
