// Mocks generated by Mockito 5.4.6 from annotations
// in viam_flutter_hotspot_provisioning_widget/test/mocks/generate_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:permission_handler/permission_handler.dart' as _i8;
import 'package:viam_flutter_hotspot_provisioning_widget/viam_flutter_hotspot_provisioning_widget.dart'
    as _i6;
import 'package:viam_sdk/protos/app/app.dart' as _i3;
import 'package:viam_sdk/protos/app/packages.dart' as _i11;
import 'package:viam_sdk/src/app/app.dart' as _i4;
import 'package:viam_sdk/src/app/billing.dart' as _i5;
import 'package:viam_sdk/src/gen/common/v1/common.pb.dart' as _i10;
import 'package:viam_sdk/viam_sdk.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeViam_0 extends _i1.SmartFake implements _i2.Viam {
  _FakeViam_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetSmartMachineStatusResponse_1 extends _i1.SmartFake
    implements _i2.GetSmartMachineStatusResponse {
  _FakeGetSmartMachineStatusResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRobot_2 extends _i1.SmartFake implements _i3.Robot {
  _FakeRobot_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppClient_3 extends _i1.SmartFake implements _i4.AppClient {
  _FakeAppClient_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppRobotClient_4 extends _i1.SmartFake
    implements _i2.AppRobotClient {
  _FakeAppRobotClient_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBillingClient_5 extends _i1.SmartFake implements _i5.BillingClient {
  _FakeBillingClient_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDataClient_6 extends _i1.SmartFake implements _i2.DataClient {
  _FakeDataClient_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProvisioningClient_7 extends _i1.SmartFake
    implements _i2.ProvisioningClient {
  _FakeProvisioningClient_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRobotClient_8 extends _i1.SmartFake implements _i2.RobotClient {
  _FakeRobotClient_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrganization_9 extends _i1.SmartFake implements _i3.Organization {
  _FakeOrganization_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeListOrganizationMembersResponse_10 extends _i1.SmartFake
    implements _i3.ListOrganizationMembersResponse {
  _FakeListOrganizationMembersResponse_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrganizationInvite_11 extends _i1.SmartFake
    implements _i3.OrganizationInvite {
  _FakeOrganizationInvite_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocation_12 extends _i1.SmartFake implements _i3.Location {
  _FakeLocation_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocationAuth_13 extends _i1.SmartFake implements _i3.LocationAuth {
  _FakeLocationAuth_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRobotPart_14 extends _i1.SmartFake implements _i3.RobotPart {
  _FakeRobotPart_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetRobotPartLogsResponse_15 extends _i1.SmartFake
    implements _i3.GetRobotPartLogsResponse {
  _FakeGetRobotPartLogsResponse_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFragment_16 extends _i1.SmartFake implements _i3.Fragment {
  _FakeFragment_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRegistryItem_17 extends _i1.SmartFake implements _i3.RegistryItem {
  _FakeRegistryItem_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreateModuleResponse_18 extends _i1.SmartFake
    implements _i3.CreateModuleResponse {
  _FakeCreateModuleResponse_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeModule_19 extends _i1.SmartFake implements _i3.Module {
  _FakeModule_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreateKeyResponse_20 extends _i1.SmartFake
    implements _i3.CreateKeyResponse {
  _FakeCreateKeyResponse_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRotateKeyResponse_21 extends _i1.SmartFake
    implements _i3.RotateKeyResponse {
  _FakeRotateKeyResponse_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreateKeyFromExistingKeyAuthorizationsResponse_22 extends _i1
    .SmartFake implements _i3.CreateKeyFromExistingKeyAuthorizationsResponse {
  _FakeCreateKeyFromExistingKeyAuthorizationsResponse_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetOrganizationMetadataResponse_23 extends _i1.SmartFake
    implements _i3.GetOrganizationMetadataResponse {
  _FakeGetOrganizationMetadataResponse_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetLocationMetadataResponse_24 extends _i1.SmartFake
    implements _i3.GetLocationMetadataResponse {
  _FakeGetLocationMetadataResponse_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetRobotMetadataResponse_25 extends _i1.SmartFake
    implements _i3.GetRobotMetadataResponse {
  _FakeGetRobotMetadataResponse_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetRobotPartMetadataResponse_26 extends _i1.SmartFake
    implements _i3.GetRobotPartMetadataResponse {
  _FakeGetRobotPartMetadataResponse_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HotspotProvisioningRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHotspotProvisioningRepository extends _i1.Mock
    implements _i6.HotspotProvisioningRepository {
  MockHotspotProvisioningRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Viam get viam => (super.noSuchMethod(
        Invocation.getter(#viam),
        returnValue: _FakeViam_0(
          this,
          Invocation.getter(#viam),
        ),
      ) as _i2.Viam);

  @override
  _i7.Future<_i2.GetSmartMachineStatusResponse> getSmartMachineStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSmartMachineStatus,
          [],
        ),
        returnValue: _i7.Future<_i2.GetSmartMachineStatusResponse>.value(
            _FakeGetSmartMachineStatusResponse_1(
          this,
          Invocation.method(
            #getSmartMachineStatus,
            [],
          ),
        )),
      ) as _i7.Future<_i2.GetSmartMachineStatusResponse>);

  @override
  _i7.Future<void> setSmartMachineCredentials({
    required String? id,
    required String? secret,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSmartMachineCredentials,
          [],
          {
            #id: id,
            #secret: secret,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setNetworkCredentials({
    required _i2.NetworkType? type,
    required String? ssid,
    required String? psk,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNetworkCredentials,
          [],
          {
            #type: type,
            #ssid: ssid,
            #psk: psk,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> exitProvisioning() => (super.noSuchMethod(
        Invocation.method(
          #exitProvisioning,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i2.NetworkInfo>> getNetworkList() => (super.noSuchMethod(
        Invocation.method(
          #getNetworkList,
          [],
        ),
        returnValue:
            _i7.Future<List<_i2.NetworkInfo>>.value(<_i2.NetworkInfo>[]),
      ) as _i7.Future<List<_i2.NetworkInfo>>);

  @override
  _i7.Future<String?> getCurrentSSID() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentSSID,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<bool> connectToSecureNetworkByPrefix({
    required String? prefix,
    required String? password,
    required bool? isWep,
    required bool? isWpa3,
    required bool? saveNetwork,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #connectToSecureNetworkByPrefix,
          [],
          {
            #prefix: prefix,
            #password: password,
            #isWep: isWep,
            #isWpa3: isWpa3,
            #saveNetwork: saveNetwork,
          },
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<_i8.PermissionStatus> requestLocationPermission() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestLocationPermission,
          [],
        ),
        returnValue:
            _i7.Future<_i8.PermissionStatus>.value(_i8.PermissionStatus.denied),
      ) as _i7.Future<_i8.PermissionStatus>);

  @override
  _i7.Future<bool> getLocationPermission() => (super.noSuchMethod(
        Invocation.method(
          #getLocationPermission,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> updateRobotPart({
    required String? partId,
    required String? robotName,
    required Map<String, dynamic>? config,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRobotPart,
          [],
          {
            #partId: partId,
            #robotName: robotName,
            #config: config,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i3.Robot> getRobot(String? robotId) => (super.noSuchMethod(
        Invocation.method(
          #getRobot,
          [robotId],
        ),
        returnValue: _i7.Future<_i3.Robot>.value(_FakeRobot_2(
          this,
          Invocation.method(
            #getRobot,
            [robotId],
          ),
        )),
      ) as _i7.Future<_i3.Robot>);

  @override
  _i7.Future<_i6.MachineStatus> calculateMachineStatus(_i3.Robot? robot) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateMachineStatus,
          [robot],
        ),
        returnValue:
            _i7.Future<_i6.MachineStatus>.value(_i6.MachineStatus.online),
      ) as _i7.Future<_i6.MachineStatus>);
}

/// A class which mocks [Viam].
///
/// See the documentation for Mockito's code generation for more information.
class MockViam extends _i1.Mock implements _i2.Viam {
  MockViam() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.AppClient get appClient => (super.noSuchMethod(
        Invocation.getter(#appClient),
        returnValue: _FakeAppClient_3(
          this,
          Invocation.getter(#appClient),
        ),
      ) as _i4.AppClient);

  @override
  _i2.AppRobotClient get appRobotClient => (super.noSuchMethod(
        Invocation.getter(#appRobotClient),
        returnValue: _FakeAppRobotClient_4(
          this,
          Invocation.getter(#appRobotClient),
        ),
      ) as _i2.AppRobotClient);

  @override
  _i5.BillingClient get billingClient => (super.noSuchMethod(
        Invocation.getter(#billingClient),
        returnValue: _FakeBillingClient_5(
          this,
          Invocation.getter(#billingClient),
        ),
      ) as _i5.BillingClient);

  @override
  _i2.DataClient get dataClient => (super.noSuchMethod(
        Invocation.getter(#dataClient),
        returnValue: _FakeDataClient_6(
          this,
          Invocation.getter(#dataClient),
        ),
      ) as _i2.DataClient);

  @override
  _i2.ProvisioningClient get provisioningClient => (super.noSuchMethod(
        Invocation.getter(#provisioningClient),
        returnValue: _FakeProvisioningClient_7(
          this,
          Invocation.getter(#provisioningClient),
        ),
      ) as _i2.ProvisioningClient);

  @override
  _i7.Future<_i2.RobotClient> getRobotClient(_i3.Robot? robot) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotClient,
          [robot],
        ),
        returnValue: _i7.Future<_i2.RobotClient>.value(_FakeRobotClient_8(
          this,
          Invocation.method(
            #getRobotClient,
            [robot],
          ),
        )),
      ) as _i7.Future<_i2.RobotClient>);
}

/// A class which mocks [ProvisioningClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockProvisioningClient extends _i1.Mock
    implements _i2.ProvisioningClient {
  MockProvisioningClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.GetSmartMachineStatusResponse> getSmartMachineStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSmartMachineStatus,
          [],
        ),
        returnValue: _i7.Future<_i2.GetSmartMachineStatusResponse>.value(
            _FakeGetSmartMachineStatusResponse_1(
          this,
          Invocation.method(
            #getSmartMachineStatus,
            [],
          ),
        )),
      ) as _i7.Future<_i2.GetSmartMachineStatusResponse>);

  @override
  _i7.Future<void> setNetworkCredentials({
    _i2.NetworkType? type = _i2.NetworkType.wifi,
    String? ssid,
    String? psk,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNetworkCredentials,
          [],
          {
            #type: type,
            #ssid: ssid,
            #psk: psk,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setSmartMachineCredentials({
    required String? id,
    required String? secret,
    String? appAddress = 'https://app.viam.com:443',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSmartMachineCredentials,
          [],
          {
            #id: id,
            #secret: secret,
            #appAddress: appAddress,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<Iterable<_i2.NetworkInfo>> getNetworkList() => (super.noSuchMethod(
        Invocation.method(
          #getNetworkList,
          [],
        ),
        returnValue:
            _i7.Future<Iterable<_i2.NetworkInfo>>.value(<_i2.NetworkInfo>[]),
      ) as _i7.Future<Iterable<_i2.NetworkInfo>>);

  @override
  _i7.Future<void> exitProvisioning() => (super.noSuchMethod(
        Invocation.method(
          #exitProvisioning,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [AppClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppClient extends _i1.Mock implements _i4.AppClient {
  MockAppClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i3.LocationSummary>> listMachineSummaries(
          String? organizationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listMachineSummaries,
          [organizationId],
        ),
        returnValue: _i7.Future<List<_i3.LocationSummary>>.value(
            <_i3.LocationSummary>[]),
      ) as _i7.Future<List<_i3.LocationSummary>>);

  @override
  _i7.Future<String> getUserIdByEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #getUserIdByEmail,
          [email],
        ),
        returnValue: _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #getUserIdByEmail,
            [email],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<_i3.Organization> createOrganization(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrganization,
          [name],
        ),
        returnValue: _i7.Future<_i3.Organization>.value(_FakeOrganization_9(
          this,
          Invocation.method(
            #createOrganization,
            [name],
          ),
        )),
      ) as _i7.Future<_i3.Organization>);

  @override
  _i7.Future<List<_i3.Organization>> listOrganizations() => (super.noSuchMethod(
        Invocation.method(
          #listOrganizations,
          [],
        ),
        returnValue:
            _i7.Future<List<_i3.Organization>>.value(<_i3.Organization>[]),
      ) as _i7.Future<List<_i3.Organization>>);

  @override
  _i7.Future<List<_i3.OrganizationIdentity>>
      getOrganizationsWithAccessToLocation(String? locationId) =>
          (super.noSuchMethod(
            Invocation.method(
              #getOrganizationsWithAccessToLocation,
              [locationId],
            ),
            returnValue: _i7.Future<List<_i3.OrganizationIdentity>>.value(
                <_i3.OrganizationIdentity>[]),
          ) as _i7.Future<List<_i3.OrganizationIdentity>>);

  @override
  _i7.Future<List<_i3.OrgDetails>> listOrganizationsByUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listOrganizationsByUser,
          [userId],
        ),
        returnValue: _i7.Future<List<_i3.OrgDetails>>.value(<_i3.OrgDetails>[]),
      ) as _i7.Future<List<_i3.OrgDetails>>);

  @override
  _i7.Future<_i3.Organization> getOrganization(String? organizationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrganization,
          [organizationId],
        ),
        returnValue: _i7.Future<_i3.Organization>.value(_FakeOrganization_9(
          this,
          Invocation.method(
            #getOrganization,
            [organizationId],
          ),
        )),
      ) as _i7.Future<_i3.Organization>);

  @override
  _i7.Future<bool> getOrganizationNamespaceAvailability(
          String? publicNamespace) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrganizationNamespaceAvailability,
          [publicNamespace],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<_i3.Organization> updateOrganization(
    String? organizationId, {
    String? name,
    String? publicNamespace,
    String? region,
    String? cid,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrganization,
          [organizationId],
          {
            #name: name,
            #publicNamespace: publicNamespace,
            #region: region,
            #cid: cid,
          },
        ),
        returnValue: _i7.Future<_i3.Organization>.value(_FakeOrganization_9(
          this,
          Invocation.method(
            #updateOrganization,
            [organizationId],
            {
              #name: name,
              #publicNamespace: publicNamespace,
              #region: region,
              #cid: cid,
            },
          ),
        )),
      ) as _i7.Future<_i3.Organization>);

  @override
  _i7.Future<void> deleteOrganization(String? organizationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOrganization,
          [organizationId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i3.ListOrganizationMembersResponse> listOrganizationMembers(
          String? organizationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listOrganizationMembers,
          [organizationId],
        ),
        returnValue: _i7.Future<_i3.ListOrganizationMembersResponse>.value(
            _FakeListOrganizationMembersResponse_10(
          this,
          Invocation.method(
            #listOrganizationMembers,
            [organizationId],
          ),
        )),
      ) as _i7.Future<_i3.ListOrganizationMembersResponse>);

  @override
  _i7.Future<_i3.OrganizationInvite> createOrganizationInvite(
    String? organizationId,
    String? email,
    List<_i2.ViamAuthorization>? authorizations, {
    bool? sendEmailInvite = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrganizationInvite,
          [
            organizationId,
            email,
            authorizations,
          ],
          {#sendEmailInvite: sendEmailInvite},
        ),
        returnValue:
            _i7.Future<_i3.OrganizationInvite>.value(_FakeOrganizationInvite_11(
          this,
          Invocation.method(
            #createOrganizationInvite,
            [
              organizationId,
              email,
              authorizations,
            ],
            {#sendEmailInvite: sendEmailInvite},
          ),
        )),
      ) as _i7.Future<_i3.OrganizationInvite>);

  @override
  _i7.Future<_i3.OrganizationInvite> updateOrganizationInviteAuthorizations(
    String? organizationId,
    String? email,
    List<_i2.ViamAuthorization>? addAuthorizations,
    List<_i2.ViamAuthorization>? removeAuthorizations,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrganizationInviteAuthorizations,
          [
            organizationId,
            email,
            addAuthorizations,
            removeAuthorizations,
          ],
        ),
        returnValue:
            _i7.Future<_i3.OrganizationInvite>.value(_FakeOrganizationInvite_11(
          this,
          Invocation.method(
            #updateOrganizationInviteAuthorizations,
            [
              organizationId,
              email,
              addAuthorizations,
              removeAuthorizations,
            ],
          ),
        )),
      ) as _i7.Future<_i3.OrganizationInvite>);

  @override
  _i7.Future<void> deleteOrganizationMember(
    String? organizationId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOrganizationMember,
          [
            organizationId,
            userId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteOrganizationInvite(
    String? organizationId,
    String? email,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOrganizationInvite,
          [
            organizationId,
            email,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i3.OrganizationInvite> resendOrganizationInvite(
    String? organizationId,
    String? email, {
    bool? sendEmailInvite = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resendOrganizationInvite,
          [
            organizationId,
            email,
          ],
          {#sendEmailInvite: sendEmailInvite},
        ),
        returnValue:
            _i7.Future<_i3.OrganizationInvite>.value(_FakeOrganizationInvite_11(
          this,
          Invocation.method(
            #resendOrganizationInvite,
            [
              organizationId,
              email,
            ],
            {#sendEmailInvite: sendEmailInvite},
          ),
        )),
      ) as _i7.Future<_i3.OrganizationInvite>);

  @override
  _i7.Future<_i3.Location> createLocation(
    String? organizationId,
    String? name, {
    String? parentLocationId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLocation,
          [
            organizationId,
            name,
          ],
          {#parentLocationId: parentLocationId},
        ),
        returnValue: _i7.Future<_i3.Location>.value(_FakeLocation_12(
          this,
          Invocation.method(
            #createLocation,
            [
              organizationId,
              name,
            ],
            {#parentLocationId: parentLocationId},
          ),
        )),
      ) as _i7.Future<_i3.Location>);

  @override
  _i7.Future<_i3.Location> getLocation(String? locationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocation,
          [locationId],
        ),
        returnValue: _i7.Future<_i3.Location>.value(_FakeLocation_12(
          this,
          Invocation.method(
            #getLocation,
            [locationId],
          ),
        )),
      ) as _i7.Future<_i3.Location>);

  @override
  _i7.Future<_i3.Location> updateLocation(
    String? locationId, {
    String? name,
    String? parentLocationId,
    String? region,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLocation,
          [locationId],
          {
            #name: name,
            #parentLocationId: parentLocationId,
            #region: region,
          },
        ),
        returnValue: _i7.Future<_i3.Location>.value(_FakeLocation_12(
          this,
          Invocation.method(
            #updateLocation,
            [locationId],
            {
              #name: name,
              #parentLocationId: parentLocationId,
              #region: region,
            },
          ),
        )),
      ) as _i7.Future<_i3.Location>);

  @override
  _i7.Future<void> deleteLocation(String? locationId) => (super.noSuchMethod(
        Invocation.method(
          #deleteLocation,
          [locationId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i3.Location>> listLocations(String? organizationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listLocations,
          [organizationId],
        ),
        returnValue: _i7.Future<List<_i3.Location>>.value(<_i3.Location>[]),
      ) as _i7.Future<List<_i3.Location>>);

  @override
  _i7.Future<void> shareLocation(
    String? locationId,
    String? organizationId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #shareLocation,
          [
            locationId,
            organizationId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> unshareLocation(
    String? locationId,
    String? organizationId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unshareLocation,
          [
            locationId,
            organizationId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i3.LocationAuth> locationAuth(String? locationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #locationAuth,
          [locationId],
        ),
        returnValue: _i7.Future<_i3.LocationAuth>.value(_FakeLocationAuth_13(
          this,
          Invocation.method(
            #locationAuth,
            [locationId],
          ),
        )),
      ) as _i7.Future<_i3.LocationAuth>);

  @override
  _i7.Future<_i3.LocationAuth> createLocationSecret(String? locationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLocationSecret,
          [locationId],
        ),
        returnValue: _i7.Future<_i3.LocationAuth>.value(_FakeLocationAuth_13(
          this,
          Invocation.method(
            #createLocationSecret,
            [locationId],
          ),
        )),
      ) as _i7.Future<_i3.LocationAuth>);

  @override
  _i7.Future<void> deleteLocationSecret(
    String? locationId,
    String? secretId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLocationSecret,
          [
            locationId,
            secretId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i3.Robot> getRobot(String? robotId) => (super.noSuchMethod(
        Invocation.method(
          #getRobot,
          [robotId],
        ),
        returnValue: _i7.Future<_i3.Robot>.value(_FakeRobot_2(
          this,
          Invocation.method(
            #getRobot,
            [robotId],
          ),
        )),
      ) as _i7.Future<_i3.Robot>);

  @override
  _i7.Future<List<_i3.RoverRentalRobot>> getRoverRentalRobots(String? orgId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRoverRentalRobots,
          [orgId],
        ),
        returnValue: _i7.Future<List<_i3.RoverRentalRobot>>.value(
            <_i3.RoverRentalRobot>[]),
      ) as _i7.Future<List<_i3.RoverRentalRobot>>);

  @override
  _i7.Future<List<_i3.RobotPart>> listRobotParts(String? robotId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listRobotParts,
          [robotId],
        ),
        returnValue: _i7.Future<List<_i3.RobotPart>>.value(<_i3.RobotPart>[]),
      ) as _i7.Future<List<_i3.RobotPart>>);

  @override
  _i7.Future<_i3.RobotPart> getRobotPart(String? partId) => (super.noSuchMethod(
        Invocation.method(
          #getRobotPart,
          [partId],
        ),
        returnValue: _i7.Future<_i3.RobotPart>.value(_FakeRobotPart_14(
          this,
          Invocation.method(
            #getRobotPart,
            [partId],
          ),
        )),
      ) as _i7.Future<_i3.RobotPart>);

  @override
  _i7.Future<_i3.GetRobotPartLogsResponse> getLogs(
    String? partId, {
    String? filter,
    String? pageToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLogs,
          [partId],
          {
            #filter: filter,
            #pageToken: pageToken,
          },
        ),
        returnValue: _i7.Future<_i3.GetRobotPartLogsResponse>.value(
            _FakeGetRobotPartLogsResponse_15(
          this,
          Invocation.method(
            #getLogs,
            [partId],
            {
              #filter: filter,
              #pageToken: pageToken,
            },
          ),
        )),
      ) as _i7.Future<_i3.GetRobotPartLogsResponse>);

  @override
  _i7.Stream<List<_i10.LogEntry>> tailLogs(
    String? partId, {
    bool? errorsOnly = false,
    String? filter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #tailLogs,
          [partId],
          {
            #errorsOnly: errorsOnly,
            #filter: filter,
          },
        ),
        returnValue: _i7.Stream<List<_i10.LogEntry>>.empty(),
      ) as _i7.Stream<List<_i10.LogEntry>>);

  @override
  _i7.Future<List<_i3.RobotPartHistoryEntry>> getRobotPartHistory(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotPartHistory,
          [id],
        ),
        returnValue: _i7.Future<List<_i3.RobotPartHistoryEntry>>.value(
            <_i3.RobotPartHistoryEntry>[]),
      ) as _i7.Future<List<_i3.RobotPartHistoryEntry>>);

  @override
  _i7.Future<_i3.RobotPart> updateRobotPart(
    String? partId,
    String? name,
    Map<String, dynamic>? robotConfig, {
    DateTime? lastKnownUpdate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRobotPart,
          [
            partId,
            name,
            robotConfig,
          ],
          {#lastKnownUpdate: lastKnownUpdate},
        ),
        returnValue: _i7.Future<_i3.RobotPart>.value(_FakeRobotPart_14(
          this,
          Invocation.method(
            #updateRobotPart,
            [
              partId,
              name,
              robotConfig,
            ],
            {#lastKnownUpdate: lastKnownUpdate},
          ),
        )),
      ) as _i7.Future<_i3.RobotPart>);

  @override
  _i7.Future<String> newRobotPart(
    String? robotId,
    String? partName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #newRobotPart,
          [
            robotId,
            partName,
          ],
        ),
        returnValue: _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #newRobotPart,
            [
              robotId,
              partName,
            ],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<void> deleteRobotPart(String? partId) => (super.noSuchMethod(
        Invocation.method(
          #deleteRobotPart,
          [partId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i3.APIKeyWithAuthorizations>> getRobotApiKeys(
          String? robotId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotApiKeys,
          [robotId],
        ),
        returnValue: _i7.Future<List<_i3.APIKeyWithAuthorizations>>.value(
            <_i3.APIKeyWithAuthorizations>[]),
      ) as _i7.Future<List<_i3.APIKeyWithAuthorizations>>);

  @override
  _i7.Future<void> markPartAsMain(String? partId) => (super.noSuchMethod(
        Invocation.method(
          #markPartAsMain,
          [partId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> markPartForRestart(String? partId) => (super.noSuchMethod(
        Invocation.method(
          #markPartForRestart,
          [partId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i3.RobotPart> createRobotPartSecret(String? partId) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRobotPartSecret,
          [partId],
        ),
        returnValue: _i7.Future<_i3.RobotPart>.value(_FakeRobotPart_14(
          this,
          Invocation.method(
            #createRobotPartSecret,
            [partId],
          ),
        )),
      ) as _i7.Future<_i3.RobotPart>);

  @override
  _i7.Future<void> deleteRobotPartSecret(
    String? partId,
    String? secretId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRobotPartSecret,
          [
            partId,
            secretId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i3.Robot>> listRobots(String? locationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listRobots,
          [locationId],
        ),
        returnValue: _i7.Future<List<_i3.Robot>>.value(<_i3.Robot>[]),
      ) as _i7.Future<List<_i3.Robot>>);

  @override
  _i7.Future<String> newMachine(
    String? name,
    String? locationId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #newMachine,
          [
            name,
            locationId,
          ],
        ),
        returnValue: _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #newMachine,
            [
              name,
              locationId,
            ],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<_i3.Robot> updateRobot(
    String? id,
    String? name,
    String? location,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRobot,
          [
            id,
            name,
            location,
          ],
        ),
        returnValue: _i7.Future<_i3.Robot>.value(_FakeRobot_2(
          this,
          Invocation.method(
            #updateRobot,
            [
              id,
              name,
              location,
            ],
          ),
        )),
      ) as _i7.Future<_i3.Robot>);

  @override
  _i7.Future<void> deleteRobot(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteRobot,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i3.Fragment>> listFragments(
    String? organizationId,
    bool? showPublic, {
    List<_i3.FragmentVisibility>? fragmentVisibility,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listFragments,
          [
            organizationId,
            showPublic,
          ],
          {#fragmentVisibility: fragmentVisibility},
        ),
        returnValue: _i7.Future<List<_i3.Fragment>>.value(<_i3.Fragment>[]),
      ) as _i7.Future<List<_i3.Fragment>>);

  @override
  _i7.Future<_i3.Fragment> getFragment(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getFragment,
          [id],
        ),
        returnValue: _i7.Future<_i3.Fragment>.value(_FakeFragment_16(
          this,
          Invocation.method(
            #getFragment,
            [id],
          ),
        )),
      ) as _i7.Future<_i3.Fragment>);

  @override
  _i7.Future<_i3.Fragment> createFragment(
    String? name,
    Map<String, dynamic>? config,
    String? organizationId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFragment,
          [
            name,
            config,
            organizationId,
          ],
        ),
        returnValue: _i7.Future<_i3.Fragment>.value(_FakeFragment_16(
          this,
          Invocation.method(
            #createFragment,
            [
              name,
              config,
              organizationId,
            ],
          ),
        )),
      ) as _i7.Future<_i3.Fragment>);

  @override
  _i7.Future<_i3.Fragment> updateFragment(
    String? id,
    String? name,
    Map<String, dynamic>? config, {
    bool? public,
    _i3.FragmentVisibility? visibility,
    DateTime? lastKnownUpdate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFragment,
          [
            id,
            name,
            config,
          ],
          {
            #public: public,
            #visibility: visibility,
            #lastKnownUpdate: lastKnownUpdate,
          },
        ),
        returnValue: _i7.Future<_i3.Fragment>.value(_FakeFragment_16(
          this,
          Invocation.method(
            #updateFragment,
            [
              id,
              name,
              config,
            ],
            {
              #public: public,
              #visibility: visibility,
              #lastKnownUpdate: lastKnownUpdate,
            },
          ),
        )),
      ) as _i7.Future<_i3.Fragment>);

  @override
  _i7.Future<void> deleteFragment(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteFragment,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> addRole(_i2.ViamAuthorization? authorization) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRole,
          [authorization],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeRole(_i2.ViamAuthorization? authorization) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeRole,
          [authorization],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> changeRole(
    _i2.ViamAuthorization? oldAuthorization,
    _i2.ViamAuthorization? newAuthorization,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeRole,
          [
            oldAuthorization,
            newAuthorization,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i3.Authorization>> listAuthorizations(
    String? organizationId, {
    List<String>? resourceIds = const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listAuthorizations,
          [organizationId],
          {#resourceIds: resourceIds},
        ),
        returnValue:
            _i7.Future<List<_i3.Authorization>>.value(<_i3.Authorization>[]),
      ) as _i7.Future<List<_i3.Authorization>>);

  @override
  _i7.Future<List<_i2.Permission>> checkPermissions(
    _i2.ResourceType? resourceType,
    String? resourceId,
    List<_i2.Permission>? permissions,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkPermissions,
          [
            resourceType,
            resourceId,
            permissions,
          ],
        ),
        returnValue: _i7.Future<List<_i2.Permission>>.value(<_i2.Permission>[]),
      ) as _i7.Future<List<_i2.Permission>>);

  @override
  _i7.Future<_i3.RegistryItem> getRegistryItem(String? itemId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRegistryItem,
          [itemId],
        ),
        returnValue: _i7.Future<_i3.RegistryItem>.value(_FakeRegistryItem_17(
          this,
          Invocation.method(
            #getRegistryItem,
            [itemId],
          ),
        )),
      ) as _i7.Future<_i3.RegistryItem>);

  @override
  _i7.Future<void> createRegistryItem(
    String? organizationId,
    String? name,
    _i11.PackageType? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRegistryItem,
          [
            organizationId,
            name,
            type,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateRegistryItem(
    String? itemId,
    _i11.PackageType? type,
    String? description,
    _i3.Visibility? visibility,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRegistryItem,
          [
            itemId,
            type,
            description,
            visibility,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i3.RegistryItem>> listRegistryItems(
    List<_i11.PackageType>? types,
    List<_i3.Visibility>? visibilities,
    List<String>? platforms,
    List<_i3.RegistryItemStatus>? statuses, {
    String? organizationId,
    String? searchTerm,
    String? pageToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listRegistryItems,
          [
            types,
            visibilities,
            platforms,
            statuses,
          ],
          {
            #organizationId: organizationId,
            #searchTerm: searchTerm,
            #pageToken: pageToken,
          },
        ),
        returnValue:
            _i7.Future<List<_i3.RegistryItem>>.value(<_i3.RegistryItem>[]),
      ) as _i7.Future<List<_i3.RegistryItem>>);

  @override
  _i7.Future<void> deleteRegistryItem(String? itemId) => (super.noSuchMethod(
        Invocation.method(
          #deleteRegistryItem,
          [itemId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i3.CreateModuleResponse> createModule(
    String? organizationId,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createModule,
          [
            organizationId,
            name,
          ],
        ),
        returnValue: _i7.Future<_i3.CreateModuleResponse>.value(
            _FakeCreateModuleResponse_18(
          this,
          Invocation.method(
            #createModule,
            [
              organizationId,
              name,
            ],
          ),
        )),
      ) as _i7.Future<_i3.CreateModuleResponse>);

  @override
  _i7.Future<String> updateModule(
    String? moduleId,
    _i3.Visibility? visibility,
    String? url,
    String? description,
    List<_i3.Model>? models,
    String? entrypoint,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateModule,
          [
            moduleId,
            visibility,
            url,
            description,
            models,
            entrypoint,
          ],
        ),
        returnValue: _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #updateModule,
            [
              moduleId,
              visibility,
              url,
              description,
              models,
              entrypoint,
            ],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> uploadModuleFile(
    _i3.ModuleFileInfo? moduleFileInfo,
    List<int>? file,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadModuleFile,
          [
            moduleFileInfo,
            file,
          ],
        ),
        returnValue: _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #uploadModuleFile,
            [
              moduleFileInfo,
              file,
            ],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<_i3.Module> getModule(String? moduleId) => (super.noSuchMethod(
        Invocation.method(
          #getModule,
          [moduleId],
        ),
        returnValue: _i7.Future<_i3.Module>.value(_FakeModule_19(
          this,
          Invocation.method(
            #getModule,
            [moduleId],
          ),
        )),
      ) as _i7.Future<_i3.Module>);

  @override
  _i7.Future<List<_i3.Module>> listModules(String? organizationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listModules,
          [organizationId],
        ),
        returnValue: _i7.Future<List<_i3.Module>>.value(<_i3.Module>[]),
      ) as _i7.Future<List<_i3.Module>>);

  @override
  _i7.Future<_i3.CreateKeyResponse> createKey(
    List<_i2.ViamAuthorization>? authorizations,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createKey,
          [
            authorizations,
            name,
          ],
        ),
        returnValue:
            _i7.Future<_i3.CreateKeyResponse>.value(_FakeCreateKeyResponse_20(
          this,
          Invocation.method(
            #createKey,
            [
              authorizations,
              name,
            ],
          ),
        )),
      ) as _i7.Future<_i3.CreateKeyResponse>);

  @override
  _i7.Future<void> deleteKey(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteKey,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i3.APIKeyWithAuthorizations>> listKeys(String? orgId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listKeys,
          [orgId],
        ),
        returnValue: _i7.Future<List<_i3.APIKeyWithAuthorizations>>.value(
            <_i3.APIKeyWithAuthorizations>[]),
      ) as _i7.Future<List<_i3.APIKeyWithAuthorizations>>);

  @override
  _i7.Future<_i3.RotateKeyResponse> rotateKey(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #rotateKey,
          [id],
        ),
        returnValue:
            _i7.Future<_i3.RotateKeyResponse>.value(_FakeRotateKeyResponse_21(
          this,
          Invocation.method(
            #rotateKey,
            [id],
          ),
        )),
      ) as _i7.Future<_i3.RotateKeyResponse>);

  @override
  _i7.Future<_i3.CreateKeyFromExistingKeyAuthorizationsResponse>
      createKeyFromExistingKeyAuthorizations(String? id) => (super.noSuchMethod(
            Invocation.method(
              #createKeyFromExistingKeyAuthorizations,
              [id],
            ),
            returnValue: _i7.Future<
                    _i3.CreateKeyFromExistingKeyAuthorizationsResponse>.value(
                _FakeCreateKeyFromExistingKeyAuthorizationsResponse_22(
              this,
              Invocation.method(
                #createKeyFromExistingKeyAuthorizations,
                [id],
              ),
            )),
          ) as _i7.Future<_i3.CreateKeyFromExistingKeyAuthorizationsResponse>);

  @override
  _i7.Future<_i3.GetOrganizationMetadataResponse> getOrganizationMetadata(
          String? organizationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrganizationMetadata,
          [organizationId],
        ),
        returnValue: _i7.Future<_i3.GetOrganizationMetadataResponse>.value(
            _FakeGetOrganizationMetadataResponse_23(
          this,
          Invocation.method(
            #getOrganizationMetadata,
            [organizationId],
          ),
        )),
      ) as _i7.Future<_i3.GetOrganizationMetadataResponse>);

  @override
  _i7.Future<void> updateOrganizationMetadata(
    String? organizationId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrganizationMetadata,
          [
            organizationId,
            data,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i3.GetLocationMetadataResponse> getLocationMetadata(
          String? locationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocationMetadata,
          [locationId],
        ),
        returnValue: _i7.Future<_i3.GetLocationMetadataResponse>.value(
            _FakeGetLocationMetadataResponse_24(
          this,
          Invocation.method(
            #getLocationMetadata,
            [locationId],
          ),
        )),
      ) as _i7.Future<_i3.GetLocationMetadataResponse>);

  @override
  _i7.Future<void> updateLocationMetadata(
    String? locationId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLocationMetadata,
          [
            locationId,
            data,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i3.GetRobotMetadataResponse> getRobotMetadata(String? robotId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotMetadata,
          [robotId],
        ),
        returnValue: _i7.Future<_i3.GetRobotMetadataResponse>.value(
            _FakeGetRobotMetadataResponse_25(
          this,
          Invocation.method(
            #getRobotMetadata,
            [robotId],
          ),
        )),
      ) as _i7.Future<_i3.GetRobotMetadataResponse>);

  @override
  _i7.Future<void> updateRobotMetadata(
    String? robotId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRobotMetadata,
          [
            robotId,
            data,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i3.GetRobotPartMetadataResponse> getRobotPartMetadata(
          String? robotPartId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotPartMetadata,
          [robotPartId],
        ),
        returnValue: _i7.Future<_i3.GetRobotPartMetadataResponse>.value(
            _FakeGetRobotPartMetadataResponse_26(
          this,
          Invocation.method(
            #getRobotPartMetadata,
            [robotPartId],
          ),
        )),
      ) as _i7.Future<_i3.GetRobotPartMetadataResponse>);

  @override
  _i7.Future<void> updateRobotPartMetadata(
    String? robotPartId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRobotPartMetadata,
          [
            robotPartId,
            data,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
