// Mocks generated by Mockito 5.4.6 from annotations
// in viam_flutter_hotspot_provisioning_widget/test/mocks/generate_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i13;

import 'package:flutter/material.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:permission_handler/permission_handler.dart' as _i9;
import 'package:viam_flutter_hotspot_provisioning_widget/viam_flutter_hotspot_provisioning_widget.dart'
    as _i3;
import 'package:viam_sdk/protos/app/app.dart' as _i4;
import 'package:viam_sdk/protos/app/packages.dart' as _i12;
import 'package:viam_sdk/src/app/app.dart' as _i5;
import 'package:viam_sdk/src/app/billing.dart' as _i6;
import 'package:viam_sdk/src/gen/common/v1/common.pb.dart' as _i11;
import 'package:viam_sdk/viam_sdk.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeViam_0 extends _i1.SmartFake implements _i2.Viam {
  _FakeViam_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePluginWifiConnectService_1 extends _i1.SmartFake
    implements _i3.PluginWifiConnectService {
  _FakePluginWifiConnectService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePermissionService_2 extends _i1.SmartFake
    implements _i3.PermissionService {
  _FakePermissionService_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetSmartMachineStatusResponse_3 extends _i1.SmartFake
    implements _i2.GetSmartMachineStatusResponse {
  _FakeGetSmartMachineStatusResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRobot_4 extends _i1.SmartFake implements _i4.Robot {
  _FakeRobot_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppClient_5 extends _i1.SmartFake implements _i5.AppClient {
  _FakeAppClient_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppRobotClient_6 extends _i1.SmartFake
    implements _i2.AppRobotClient {
  _FakeAppRobotClient_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBillingClient_7 extends _i1.SmartFake implements _i6.BillingClient {
  _FakeBillingClient_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDataClient_8 extends _i1.SmartFake implements _i2.DataClient {
  _FakeDataClient_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProvisioningClient_9 extends _i1.SmartFake
    implements _i2.ProvisioningClient {
  _FakeProvisioningClient_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRobotClient_10 extends _i1.SmartFake implements _i2.RobotClient {
  _FakeRobotClient_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrganization_11 extends _i1.SmartFake implements _i4.Organization {
  _FakeOrganization_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeListOrganizationMembersResponse_12 extends _i1.SmartFake
    implements _i4.ListOrganizationMembersResponse {
  _FakeListOrganizationMembersResponse_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrganizationInvite_13 extends _i1.SmartFake
    implements _i4.OrganizationInvite {
  _FakeOrganizationInvite_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocation_14 extends _i1.SmartFake implements _i4.Location {
  _FakeLocation_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocationAuth_15 extends _i1.SmartFake implements _i4.LocationAuth {
  _FakeLocationAuth_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRobotPart_16 extends _i1.SmartFake implements _i4.RobotPart {
  _FakeRobotPart_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetRobotPartLogsResponse_17 extends _i1.SmartFake
    implements _i4.GetRobotPartLogsResponse {
  _FakeGetRobotPartLogsResponse_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFragment_18 extends _i1.SmartFake implements _i4.Fragment {
  _FakeFragment_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRegistryItem_19 extends _i1.SmartFake implements _i4.RegistryItem {
  _FakeRegistryItem_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreateModuleResponse_20 extends _i1.SmartFake
    implements _i4.CreateModuleResponse {
  _FakeCreateModuleResponse_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeModule_21 extends _i1.SmartFake implements _i4.Module {
  _FakeModule_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreateKeyResponse_22 extends _i1.SmartFake
    implements _i4.CreateKeyResponse {
  _FakeCreateKeyResponse_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRotateKeyResponse_23 extends _i1.SmartFake
    implements _i4.RotateKeyResponse {
  _FakeRotateKeyResponse_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreateKeyFromExistingKeyAuthorizationsResponse_24 extends _i1
    .SmartFake implements _i4.CreateKeyFromExistingKeyAuthorizationsResponse {
  _FakeCreateKeyFromExistingKeyAuthorizationsResponse_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetOrganizationMetadataResponse_25 extends _i1.SmartFake
    implements _i4.GetOrganizationMetadataResponse {
  _FakeGetOrganizationMetadataResponse_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetLocationMetadataResponse_26 extends _i1.SmartFake
    implements _i4.GetLocationMetadataResponse {
  _FakeGetLocationMetadataResponse_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetRobotMetadataResponse_27 extends _i1.SmartFake
    implements _i4.GetRobotMetadataResponse {
  _FakeGetRobotMetadataResponse_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetRobotPartMetadataResponse_28 extends _i1.SmartFake
    implements _i4.GetRobotPartMetadataResponse {
  _FakeGetRobotPartMetadataResponse_28(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePageController_29 extends _i1.SmartFake
    implements _i7.PageController {
  _FakePageController_29(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHotspotCredentialsInputViewModel_30 extends _i1.SmartFake
    implements _i3.HotspotCredentialsInputViewModel {
  _FakeHotspotCredentialsInputViewModel_30(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNetworkSelectionViewModel_31 extends _i1.SmartFake
    implements _i3.NetworkSelectionViewModel {
  _FakeNetworkSelectionViewModel_31(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePasswordInputViewModel_32 extends _i1.SmartFake
    implements _i3.PasswordInputViewModel {
  _FakePasswordInputViewModel_32(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConfirmationViewModel_33 extends _i1.SmartFake
    implements _i3.ConfirmationViewModel {
  _FakeConfirmationViewModel_33(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeScrollPosition_34 extends _i1.SmartFake
    implements _i7.ScrollPosition {
  _FakeScrollPosition_34(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHotspotProvisioningRepository_35 extends _i1.SmartFake
    implements _i3.HotspotProvisioningRepository {
  _FakeHotspotProvisioningRepository_35(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIconData_36 extends _i1.SmartFake implements _i7.IconData {
  _FakeIconData_36(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTextEditingController_37 extends _i1.SmartFake
    implements _i7.TextEditingController {
  _FakeTextEditingController_37(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HotspotProvisioningRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHotspotProvisioningRepository extends _i1.Mock
    implements _i3.HotspotProvisioningRepository {
  MockHotspotProvisioningRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Viam get viam => (super.noSuchMethod(
        Invocation.getter(#viam),
        returnValue: _FakeViam_0(
          this,
          Invocation.getter(#viam),
        ),
      ) as _i2.Viam);

  @override
  _i3.PluginWifiConnectService get pluginWifiConnectService =>
      (super.noSuchMethod(
        Invocation.getter(#pluginWifiConnectService),
        returnValue: _FakePluginWifiConnectService_1(
          this,
          Invocation.getter(#pluginWifiConnectService),
        ),
      ) as _i3.PluginWifiConnectService);

  @override
  _i3.PermissionService get permissionService => (super.noSuchMethod(
        Invocation.getter(#permissionService),
        returnValue: _FakePermissionService_2(
          this,
          Invocation.getter(#permissionService),
        ),
      ) as _i3.PermissionService);

  @override
  _i8.Future<_i2.GetSmartMachineStatusResponse> getSmartMachineStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSmartMachineStatus,
          [],
        ),
        returnValue: _i8.Future<_i2.GetSmartMachineStatusResponse>.value(
            _FakeGetSmartMachineStatusResponse_3(
          this,
          Invocation.method(
            #getSmartMachineStatus,
            [],
          ),
        )),
      ) as _i8.Future<_i2.GetSmartMachineStatusResponse>);

  @override
  _i8.Future<bool> isDeviceReachable(
          {Duration? timeout = const Duration(seconds: 10)}) =>
      (super.noSuchMethod(
        Invocation.method(
          #isDeviceReachable,
          [],
          {#timeout: timeout},
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> setSmartMachineCredentials({
    required String? id,
    required String? secret,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSmartMachineCredentials,
          [],
          {
            #id: id,
            #secret: secret,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setNetworkCredentialsOnOldAgent({
    required _i2.NetworkType? type,
    required String? ssid,
    required String? psk,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNetworkCredentialsOnOldAgent,
          [],
          {
            #type: type,
            #ssid: ssid,
            #psk: psk,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setNetworkCredentials({
    required _i2.NetworkType? type,
    required String? ssid,
    required String? psk,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNetworkCredentials,
          [],
          {
            #type: type,
            #ssid: ssid,
            #psk: psk,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> exitProvisioning() => (super.noSuchMethod(
        Invocation.method(
          #exitProvisioning,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i2.NetworkInfo>> getNetworkList() => (super.noSuchMethod(
        Invocation.method(
          #getNetworkList,
          [],
        ),
        returnValue:
            _i8.Future<List<_i2.NetworkInfo>>.value(<_i2.NetworkInfo>[]),
      ) as _i8.Future<List<_i2.NetworkInfo>>);

  @override
  _i8.Future<String?> getCurrentSSID() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentSSID,
          [],
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<bool> connectToSecureNetworkByPrefix({
    required String? prefix,
    required String? password,
    required bool? isWep,
    required bool? isWpa3,
    required bool? saveNetwork,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #connectToSecureNetworkByPrefix,
          [],
          {
            #prefix: prefix,
            #password: password,
            #isWep: isWep,
            #isWpa3: isWpa3,
            #saveNetwork: saveNetwork,
          },
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<_i9.PermissionStatus> requestLocationPermission() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestLocationPermission,
          [],
        ),
        returnValue:
            _i8.Future<_i9.PermissionStatus>.value(_i9.PermissionStatus.denied),
      ) as _i8.Future<_i9.PermissionStatus>);

  @override
  _i8.Future<bool> getLocationPermission() => (super.noSuchMethod(
        Invocation.method(
          #getLocationPermission,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> updateRobotPart({
    required String? partId,
    required String? robotName,
    required Map<String, dynamic>? config,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRobotPart,
          [],
          {
            #partId: partId,
            #robotName: robotName,
            #config: config,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i4.Robot> getRobot(String? robotId) => (super.noSuchMethod(
        Invocation.method(
          #getRobot,
          [robotId],
        ),
        returnValue: _i8.Future<_i4.Robot>.value(_FakeRobot_4(
          this,
          Invocation.method(
            #getRobot,
            [robotId],
          ),
        )),
      ) as _i8.Future<_i4.Robot>);

  @override
  _i8.Future<_i3.MachineStatus> calculateMachineStatus(_i4.Robot? robot) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateMachineStatus,
          [robot],
        ),
        returnValue:
            _i8.Future<_i3.MachineStatus>.value(_i3.MachineStatus.online),
      ) as _i8.Future<_i3.MachineStatus>);
}

/// A class which mocks [Viam].
///
/// See the documentation for Mockito's code generation for more information.
class MockViam extends _i1.Mock implements _i2.Viam {
  MockViam() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.AppClient get appClient => (super.noSuchMethod(
        Invocation.getter(#appClient),
        returnValue: _FakeAppClient_5(
          this,
          Invocation.getter(#appClient),
        ),
      ) as _i5.AppClient);

  @override
  _i2.AppRobotClient get appRobotClient => (super.noSuchMethod(
        Invocation.getter(#appRobotClient),
        returnValue: _FakeAppRobotClient_6(
          this,
          Invocation.getter(#appRobotClient),
        ),
      ) as _i2.AppRobotClient);

  @override
  _i6.BillingClient get billingClient => (super.noSuchMethod(
        Invocation.getter(#billingClient),
        returnValue: _FakeBillingClient_7(
          this,
          Invocation.getter(#billingClient),
        ),
      ) as _i6.BillingClient);

  @override
  _i2.DataClient get dataClient => (super.noSuchMethod(
        Invocation.getter(#dataClient),
        returnValue: _FakeDataClient_8(
          this,
          Invocation.getter(#dataClient),
        ),
      ) as _i2.DataClient);

  @override
  _i2.ProvisioningClient get provisioningClient => (super.noSuchMethod(
        Invocation.getter(#provisioningClient),
        returnValue: _FakeProvisioningClient_9(
          this,
          Invocation.getter(#provisioningClient),
        ),
      ) as _i2.ProvisioningClient);

  @override
  _i8.Future<_i2.RobotClient> getRobotClient(_i4.Robot? robot) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotClient,
          [robot],
        ),
        returnValue: _i8.Future<_i2.RobotClient>.value(_FakeRobotClient_10(
          this,
          Invocation.method(
            #getRobotClient,
            [robot],
          ),
        )),
      ) as _i8.Future<_i2.RobotClient>);
}

/// A class which mocks [ProvisioningClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockProvisioningClient extends _i1.Mock
    implements _i2.ProvisioningClient {
  MockProvisioningClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.GetSmartMachineStatusResponse> getSmartMachineStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSmartMachineStatus,
          [],
        ),
        returnValue: _i8.Future<_i2.GetSmartMachineStatusResponse>.value(
            _FakeGetSmartMachineStatusResponse_3(
          this,
          Invocation.method(
            #getSmartMachineStatus,
            [],
          ),
        )),
      ) as _i8.Future<_i2.GetSmartMachineStatusResponse>);

  @override
  _i8.Future<void> setNetworkCredentials({
    _i2.NetworkType? type = _i2.NetworkType.wifi,
    String? ssid,
    String? psk,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNetworkCredentials,
          [],
          {
            #type: type,
            #ssid: ssid,
            #psk: psk,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setSmartMachineCredentials({
    required String? id,
    String? secret,
    String? apiKeyId,
    String? apiKey,
    String? appAddress = 'https://app.viam.com:443',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSmartMachineCredentials,
          [],
          {
            #id: id,
            #secret: secret,
            #apiKeyId: apiKeyId,
            #apiKey: apiKey,
            #appAddress: appAddress,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<Iterable<_i2.NetworkInfo>> getNetworkList() => (super.noSuchMethod(
        Invocation.method(
          #getNetworkList,
          [],
        ),
        returnValue:
            _i8.Future<Iterable<_i2.NetworkInfo>>.value(<_i2.NetworkInfo>[]),
      ) as _i8.Future<Iterable<_i2.NetworkInfo>>);

  @override
  _i8.Future<void> exitProvisioning() => (super.noSuchMethod(
        Invocation.method(
          #exitProvisioning,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [AppClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppClient extends _i1.Mock implements _i5.AppClient {
  MockAppClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i4.LocationSummary>> listMachineSummaries(
          String? organizationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listMachineSummaries,
          [organizationId],
        ),
        returnValue: _i8.Future<List<_i4.LocationSummary>>.value(
            <_i4.LocationSummary>[]),
      ) as _i8.Future<List<_i4.LocationSummary>>);

  @override
  _i8.Future<String> getUserIdByEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #getUserIdByEmail,
          [email],
        ),
        returnValue: _i8.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #getUserIdByEmail,
            [email],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<_i4.Organization> createOrganization(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrganization,
          [name],
        ),
        returnValue: _i8.Future<_i4.Organization>.value(_FakeOrganization_11(
          this,
          Invocation.method(
            #createOrganization,
            [name],
          ),
        )),
      ) as _i8.Future<_i4.Organization>);

  @override
  _i8.Future<List<_i4.Organization>> listOrganizations() => (super.noSuchMethod(
        Invocation.method(
          #listOrganizations,
          [],
        ),
        returnValue:
            _i8.Future<List<_i4.Organization>>.value(<_i4.Organization>[]),
      ) as _i8.Future<List<_i4.Organization>>);

  @override
  _i8.Future<List<_i4.OrganizationIdentity>>
      getOrganizationsWithAccessToLocation(String? locationId) =>
          (super.noSuchMethod(
            Invocation.method(
              #getOrganizationsWithAccessToLocation,
              [locationId],
            ),
            returnValue: _i8.Future<List<_i4.OrganizationIdentity>>.value(
                <_i4.OrganizationIdentity>[]),
          ) as _i8.Future<List<_i4.OrganizationIdentity>>);

  @override
  _i8.Future<List<_i4.OrgDetails>> listOrganizationsByUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listOrganizationsByUser,
          [userId],
        ),
        returnValue: _i8.Future<List<_i4.OrgDetails>>.value(<_i4.OrgDetails>[]),
      ) as _i8.Future<List<_i4.OrgDetails>>);

  @override
  _i8.Future<_i4.Organization> getOrganization(String? organizationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrganization,
          [organizationId],
        ),
        returnValue: _i8.Future<_i4.Organization>.value(_FakeOrganization_11(
          this,
          Invocation.method(
            #getOrganization,
            [organizationId],
          ),
        )),
      ) as _i8.Future<_i4.Organization>);

  @override
  _i8.Future<bool> getOrganizationNamespaceAvailability(
          String? publicNamespace) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrganizationNamespaceAvailability,
          [publicNamespace],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<_i4.Organization> updateOrganization(
    String? organizationId, {
    String? name,
    String? publicNamespace,
    String? region,
    String? cid,
    _i4.FragmentImportList? defaultFragments,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrganization,
          [organizationId],
          {
            #name: name,
            #publicNamespace: publicNamespace,
            #region: region,
            #cid: cid,
            #defaultFragments: defaultFragments,
          },
        ),
        returnValue: _i8.Future<_i4.Organization>.value(_FakeOrganization_11(
          this,
          Invocation.method(
            #updateOrganization,
            [organizationId],
            {
              #name: name,
              #publicNamespace: publicNamespace,
              #region: region,
              #cid: cid,
              #defaultFragments: defaultFragments,
            },
          ),
        )),
      ) as _i8.Future<_i4.Organization>);

  @override
  _i8.Future<void> deleteOrganization(String? organizationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOrganization,
          [organizationId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i4.ListOrganizationMembersResponse> listOrganizationMembers(
          String? organizationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listOrganizationMembers,
          [organizationId],
        ),
        returnValue: _i8.Future<_i4.ListOrganizationMembersResponse>.value(
            _FakeListOrganizationMembersResponse_12(
          this,
          Invocation.method(
            #listOrganizationMembers,
            [organizationId],
          ),
        )),
      ) as _i8.Future<_i4.ListOrganizationMembersResponse>);

  @override
  _i8.Future<_i4.OrganizationInvite> createOrganizationInvite(
    String? organizationId,
    String? email,
    List<_i2.ViamAuthorization>? authorizations, {
    bool? sendEmailInvite = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrganizationInvite,
          [
            organizationId,
            email,
            authorizations,
          ],
          {#sendEmailInvite: sendEmailInvite},
        ),
        returnValue:
            _i8.Future<_i4.OrganizationInvite>.value(_FakeOrganizationInvite_13(
          this,
          Invocation.method(
            #createOrganizationInvite,
            [
              organizationId,
              email,
              authorizations,
            ],
            {#sendEmailInvite: sendEmailInvite},
          ),
        )),
      ) as _i8.Future<_i4.OrganizationInvite>);

  @override
  _i8.Future<_i4.OrganizationInvite> updateOrganizationInviteAuthorizations(
    String? organizationId,
    String? email,
    List<_i2.ViamAuthorization>? addAuthorizations,
    List<_i2.ViamAuthorization>? removeAuthorizations,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrganizationInviteAuthorizations,
          [
            organizationId,
            email,
            addAuthorizations,
            removeAuthorizations,
          ],
        ),
        returnValue:
            _i8.Future<_i4.OrganizationInvite>.value(_FakeOrganizationInvite_13(
          this,
          Invocation.method(
            #updateOrganizationInviteAuthorizations,
            [
              organizationId,
              email,
              addAuthorizations,
              removeAuthorizations,
            ],
          ),
        )),
      ) as _i8.Future<_i4.OrganizationInvite>);

  @override
  _i8.Future<void> deleteOrganizationMember(
    String? organizationId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOrganizationMember,
          [
            organizationId,
            userId,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteOrganizationInvite(
    String? organizationId,
    String? email,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOrganizationInvite,
          [
            organizationId,
            email,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i4.OrganizationInvite> resendOrganizationInvite(
    String? organizationId,
    String? email, {
    bool? sendEmailInvite = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resendOrganizationInvite,
          [
            organizationId,
            email,
          ],
          {#sendEmailInvite: sendEmailInvite},
        ),
        returnValue:
            _i8.Future<_i4.OrganizationInvite>.value(_FakeOrganizationInvite_13(
          this,
          Invocation.method(
            #resendOrganizationInvite,
            [
              organizationId,
              email,
            ],
            {#sendEmailInvite: sendEmailInvite},
          ),
        )),
      ) as _i8.Future<_i4.OrganizationInvite>);

  @override
  _i8.Future<_i4.Location> createLocation(
    String? organizationId,
    String? name, {
    String? parentLocationId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLocation,
          [
            organizationId,
            name,
          ],
          {#parentLocationId: parentLocationId},
        ),
        returnValue: _i8.Future<_i4.Location>.value(_FakeLocation_14(
          this,
          Invocation.method(
            #createLocation,
            [
              organizationId,
              name,
            ],
            {#parentLocationId: parentLocationId},
          ),
        )),
      ) as _i8.Future<_i4.Location>);

  @override
  _i8.Future<_i4.Location> getLocation(String? locationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocation,
          [locationId],
        ),
        returnValue: _i8.Future<_i4.Location>.value(_FakeLocation_14(
          this,
          Invocation.method(
            #getLocation,
            [locationId],
          ),
        )),
      ) as _i8.Future<_i4.Location>);

  @override
  _i8.Future<_i4.Location> updateLocation(
    String? locationId, {
    String? name,
    String? parentLocationId,
    String? region,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLocation,
          [locationId],
          {
            #name: name,
            #parentLocationId: parentLocationId,
            #region: region,
          },
        ),
        returnValue: _i8.Future<_i4.Location>.value(_FakeLocation_14(
          this,
          Invocation.method(
            #updateLocation,
            [locationId],
            {
              #name: name,
              #parentLocationId: parentLocationId,
              #region: region,
            },
          ),
        )),
      ) as _i8.Future<_i4.Location>);

  @override
  _i8.Future<void> deleteLocation(String? locationId) => (super.noSuchMethod(
        Invocation.method(
          #deleteLocation,
          [locationId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i4.Location>> listLocations(String? organizationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listLocations,
          [organizationId],
        ),
        returnValue: _i8.Future<List<_i4.Location>>.value(<_i4.Location>[]),
      ) as _i8.Future<List<_i4.Location>>);

  @override
  _i8.Future<void> shareLocation(
    String? locationId,
    String? organizationId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #shareLocation,
          [
            locationId,
            organizationId,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> unshareLocation(
    String? locationId,
    String? organizationId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unshareLocation,
          [
            locationId,
            organizationId,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i4.LocationAuth> locationAuth(String? locationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #locationAuth,
          [locationId],
        ),
        returnValue: _i8.Future<_i4.LocationAuth>.value(_FakeLocationAuth_15(
          this,
          Invocation.method(
            #locationAuth,
            [locationId],
          ),
        )),
      ) as _i8.Future<_i4.LocationAuth>);

  @override
  _i8.Future<_i4.LocationAuth> createLocationSecret(String? locationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLocationSecret,
          [locationId],
        ),
        returnValue: _i8.Future<_i4.LocationAuth>.value(_FakeLocationAuth_15(
          this,
          Invocation.method(
            #createLocationSecret,
            [locationId],
          ),
        )),
      ) as _i8.Future<_i4.LocationAuth>);

  @override
  _i8.Future<void> deleteLocationSecret(
    String? locationId,
    String? secretId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLocationSecret,
          [
            locationId,
            secretId,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i4.Robot> getRobot(String? robotId) => (super.noSuchMethod(
        Invocation.method(
          #getRobot,
          [robotId],
        ),
        returnValue: _i8.Future<_i4.Robot>.value(_FakeRobot_4(
          this,
          Invocation.method(
            #getRobot,
            [robotId],
          ),
        )),
      ) as _i8.Future<_i4.Robot>);

  @override
  _i8.Future<List<_i4.RoverRentalRobot>> getRoverRentalRobots(String? orgId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRoverRentalRobots,
          [orgId],
        ),
        returnValue: _i8.Future<List<_i4.RoverRentalRobot>>.value(
            <_i4.RoverRentalRobot>[]),
      ) as _i8.Future<List<_i4.RoverRentalRobot>>);

  @override
  _i8.Future<List<_i4.RobotPart>> listRobotParts(String? robotId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listRobotParts,
          [robotId],
        ),
        returnValue: _i8.Future<List<_i4.RobotPart>>.value(<_i4.RobotPart>[]),
      ) as _i8.Future<List<_i4.RobotPart>>);

  @override
  _i8.Future<_i4.RobotPart> getRobotPart(String? partId) => (super.noSuchMethod(
        Invocation.method(
          #getRobotPart,
          [partId],
        ),
        returnValue: _i8.Future<_i4.RobotPart>.value(_FakeRobotPart_16(
          this,
          Invocation.method(
            #getRobotPart,
            [partId],
          ),
        )),
      ) as _i8.Future<_i4.RobotPart>);

  @override
  _i8.Future<_i4.GetRobotPartLogsResponse> getLogs(
    String? partId, {
    String? filter,
    String? pageToken,
    Iterable<String>? levels,
    int? limit,
    DateTime? startTime,
    DateTime? endTime,
    String? source,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLogs,
          [partId],
          {
            #filter: filter,
            #pageToken: pageToken,
            #levels: levels,
            #limit: limit,
            #startTime: startTime,
            #endTime: endTime,
            #source: source,
          },
        ),
        returnValue: _i8.Future<_i4.GetRobotPartLogsResponse>.value(
            _FakeGetRobotPartLogsResponse_17(
          this,
          Invocation.method(
            #getLogs,
            [partId],
            {
              #filter: filter,
              #pageToken: pageToken,
              #levels: levels,
              #limit: limit,
              #startTime: startTime,
              #endTime: endTime,
              #source: source,
            },
          ),
        )),
      ) as _i8.Future<_i4.GetRobotPartLogsResponse>);

  @override
  _i8.Stream<List<_i11.LogEntry>> tailLogs(
    String? partId, {
    bool? errorsOnly = false,
    String? filter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #tailLogs,
          [partId],
          {
            #errorsOnly: errorsOnly,
            #filter: filter,
          },
        ),
        returnValue: _i8.Stream<List<_i11.LogEntry>>.empty(),
      ) as _i8.Stream<List<_i11.LogEntry>>);

  @override
  _i8.Future<List<_i4.RobotPartHistoryEntry>> getRobotPartHistory(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotPartHistory,
          [id],
        ),
        returnValue: _i8.Future<List<_i4.RobotPartHistoryEntry>>.value(
            <_i4.RobotPartHistoryEntry>[]),
      ) as _i8.Future<List<_i4.RobotPartHistoryEntry>>);

  @override
  _i8.Future<_i4.RobotPart> updateRobotPart(
    String? partId,
    String? name,
    Map<String, dynamic>? robotConfig, {
    DateTime? lastKnownUpdate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRobotPart,
          [
            partId,
            name,
            robotConfig,
          ],
          {#lastKnownUpdate: lastKnownUpdate},
        ),
        returnValue: _i8.Future<_i4.RobotPart>.value(_FakeRobotPart_16(
          this,
          Invocation.method(
            #updateRobotPart,
            [
              partId,
              name,
              robotConfig,
            ],
            {#lastKnownUpdate: lastKnownUpdate},
          ),
        )),
      ) as _i8.Future<_i4.RobotPart>);

  @override
  _i8.Future<String> newRobotPart(
    String? robotId,
    String? partName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #newRobotPart,
          [
            robotId,
            partName,
          ],
        ),
        returnValue: _i8.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #newRobotPart,
            [
              robotId,
              partName,
            ],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<void> deleteRobotPart(String? partId) => (super.noSuchMethod(
        Invocation.method(
          #deleteRobotPart,
          [partId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i4.APIKeyWithAuthorizations>> getRobotApiKeys(
          String? robotId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotApiKeys,
          [robotId],
        ),
        returnValue: _i8.Future<List<_i4.APIKeyWithAuthorizations>>.value(
            <_i4.APIKeyWithAuthorizations>[]),
      ) as _i8.Future<List<_i4.APIKeyWithAuthorizations>>);

  @override
  _i8.Future<void> markPartAsMain(String? partId) => (super.noSuchMethod(
        Invocation.method(
          #markPartAsMain,
          [partId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> markPartForRestart(String? partId) => (super.noSuchMethod(
        Invocation.method(
          #markPartForRestart,
          [partId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i4.RobotPart> createRobotPartSecret(String? partId) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRobotPartSecret,
          [partId],
        ),
        returnValue: _i8.Future<_i4.RobotPart>.value(_FakeRobotPart_16(
          this,
          Invocation.method(
            #createRobotPartSecret,
            [partId],
          ),
        )),
      ) as _i8.Future<_i4.RobotPart>);

  @override
  _i8.Future<void> deleteRobotPartSecret(
    String? partId,
    String? secretId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRobotPartSecret,
          [
            partId,
            secretId,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i4.Robot>> listRobots(String? locationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listRobots,
          [locationId],
        ),
        returnValue: _i8.Future<List<_i4.Robot>>.value(<_i4.Robot>[]),
      ) as _i8.Future<List<_i4.Robot>>);

  @override
  _i8.Future<String> newMachine(
    String? name,
    String? locationId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #newMachine,
          [
            name,
            locationId,
          ],
        ),
        returnValue: _i8.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #newMachine,
            [
              name,
              locationId,
            ],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<_i4.Robot> updateRobot(
    String? id,
    String? name,
    String? location,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRobot,
          [
            id,
            name,
            location,
          ],
        ),
        returnValue: _i8.Future<_i4.Robot>.value(_FakeRobot_4(
          this,
          Invocation.method(
            #updateRobot,
            [
              id,
              name,
              location,
            ],
          ),
        )),
      ) as _i8.Future<_i4.Robot>);

  @override
  _i8.Future<void> deleteRobot(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteRobot,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i4.Fragment>> listFragments(
    String? organizationId,
    bool? showPublic, {
    List<_i4.FragmentVisibility>? fragmentVisibility,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listFragments,
          [
            organizationId,
            showPublic,
          ],
          {#fragmentVisibility: fragmentVisibility},
        ),
        returnValue: _i8.Future<List<_i4.Fragment>>.value(<_i4.Fragment>[]),
      ) as _i8.Future<List<_i4.Fragment>>);

  @override
  _i8.Future<_i4.Fragment> getFragment(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getFragment,
          [id],
        ),
        returnValue: _i8.Future<_i4.Fragment>.value(_FakeFragment_18(
          this,
          Invocation.method(
            #getFragment,
            [id],
          ),
        )),
      ) as _i8.Future<_i4.Fragment>);

  @override
  _i8.Future<_i4.Fragment> createFragment(
    String? name,
    Map<String, dynamic>? config,
    String? organizationId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFragment,
          [
            name,
            config,
            organizationId,
          ],
        ),
        returnValue: _i8.Future<_i4.Fragment>.value(_FakeFragment_18(
          this,
          Invocation.method(
            #createFragment,
            [
              name,
              config,
              organizationId,
            ],
          ),
        )),
      ) as _i8.Future<_i4.Fragment>);

  @override
  _i8.Future<_i4.Fragment> updateFragment(
    String? id,
    String? name,
    Map<String, dynamic>? config, {
    bool? public,
    _i4.FragmentVisibility? visibility,
    DateTime? lastKnownUpdate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFragment,
          [
            id,
            name,
            config,
          ],
          {
            #public: public,
            #visibility: visibility,
            #lastKnownUpdate: lastKnownUpdate,
          },
        ),
        returnValue: _i8.Future<_i4.Fragment>.value(_FakeFragment_18(
          this,
          Invocation.method(
            #updateFragment,
            [
              id,
              name,
              config,
            ],
            {
              #public: public,
              #visibility: visibility,
              #lastKnownUpdate: lastKnownUpdate,
            },
          ),
        )),
      ) as _i8.Future<_i4.Fragment>);

  @override
  _i8.Future<void> deleteFragment(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteFragment,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addRole(_i2.ViamAuthorization? authorization) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRole,
          [authorization],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> removeRole(_i2.ViamAuthorization? authorization) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeRole,
          [authorization],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> changeRole(
    _i2.ViamAuthorization? oldAuthorization,
    _i2.ViamAuthorization? newAuthorization,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeRole,
          [
            oldAuthorization,
            newAuthorization,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i4.Authorization>> listAuthorizations(
    String? organizationId, {
    List<String>? resourceIds = const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listAuthorizations,
          [organizationId],
          {#resourceIds: resourceIds},
        ),
        returnValue:
            _i8.Future<List<_i4.Authorization>>.value(<_i4.Authorization>[]),
      ) as _i8.Future<List<_i4.Authorization>>);

  @override
  _i8.Future<List<_i2.Permission>> checkPermissions(
    _i2.ResourceType? resourceType,
    String? resourceId,
    List<_i2.Permission>? permissions,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkPermissions,
          [
            resourceType,
            resourceId,
            permissions,
          ],
        ),
        returnValue: _i8.Future<List<_i2.Permission>>.value(<_i2.Permission>[]),
      ) as _i8.Future<List<_i2.Permission>>);

  @override
  _i8.Future<_i4.RegistryItem> getRegistryItem(String? itemId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRegistryItem,
          [itemId],
        ),
        returnValue: _i8.Future<_i4.RegistryItem>.value(_FakeRegistryItem_19(
          this,
          Invocation.method(
            #getRegistryItem,
            [itemId],
          ),
        )),
      ) as _i8.Future<_i4.RegistryItem>);

  @override
  _i8.Future<void> createRegistryItem(
    String? organizationId,
    String? name,
    _i12.PackageType? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRegistryItem,
          [
            organizationId,
            name,
            type,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateRegistryItem(
    String? itemId,
    _i12.PackageType? type,
    String? description,
    _i4.Visibility? visibility,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRegistryItem,
          [
            itemId,
            type,
            description,
            visibility,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i4.RegistryItem>> listRegistryItems(
    List<_i12.PackageType>? types,
    List<_i4.Visibility>? visibilities,
    List<String>? platforms,
    List<_i4.RegistryItemStatus>? statuses, {
    String? organizationId,
    String? searchTerm,
    String? pageToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listRegistryItems,
          [
            types,
            visibilities,
            platforms,
            statuses,
          ],
          {
            #organizationId: organizationId,
            #searchTerm: searchTerm,
            #pageToken: pageToken,
          },
        ),
        returnValue:
            _i8.Future<List<_i4.RegistryItem>>.value(<_i4.RegistryItem>[]),
      ) as _i8.Future<List<_i4.RegistryItem>>);

  @override
  _i8.Future<void> deleteRegistryItem(String? itemId) => (super.noSuchMethod(
        Invocation.method(
          #deleteRegistryItem,
          [itemId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i4.CreateModuleResponse> createModule(
    String? organizationId,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createModule,
          [
            organizationId,
            name,
          ],
        ),
        returnValue: _i8.Future<_i4.CreateModuleResponse>.value(
            _FakeCreateModuleResponse_20(
          this,
          Invocation.method(
            #createModule,
            [
              organizationId,
              name,
            ],
          ),
        )),
      ) as _i8.Future<_i4.CreateModuleResponse>);

  @override
  _i8.Future<String> updateModule(
    String? moduleId,
    _i4.Visibility? visibility,
    String? url,
    String? description,
    List<_i4.Model>? models,
    String? entrypoint,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateModule,
          [
            moduleId,
            visibility,
            url,
            description,
            models,
            entrypoint,
          ],
        ),
        returnValue: _i8.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #updateModule,
            [
              moduleId,
              visibility,
              url,
              description,
              models,
              entrypoint,
            ],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<String> uploadModuleFile(
    _i4.ModuleFileInfo? moduleFileInfo,
    List<int>? file,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadModuleFile,
          [
            moduleFileInfo,
            file,
          ],
        ),
        returnValue: _i8.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #uploadModuleFile,
            [
              moduleFileInfo,
              file,
            ],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<_i4.Module> getModule(String? moduleId) => (super.noSuchMethod(
        Invocation.method(
          #getModule,
          [moduleId],
        ),
        returnValue: _i8.Future<_i4.Module>.value(_FakeModule_21(
          this,
          Invocation.method(
            #getModule,
            [moduleId],
          ),
        )),
      ) as _i8.Future<_i4.Module>);

  @override
  _i8.Future<List<_i4.Module>> listModules(String? organizationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listModules,
          [organizationId],
        ),
        returnValue: _i8.Future<List<_i4.Module>>.value(<_i4.Module>[]),
      ) as _i8.Future<List<_i4.Module>>);

  @override
  _i8.Future<_i4.CreateKeyResponse> createKey(
    List<_i2.ViamAuthorization>? authorizations,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createKey,
          [
            authorizations,
            name,
          ],
        ),
        returnValue:
            _i8.Future<_i4.CreateKeyResponse>.value(_FakeCreateKeyResponse_22(
          this,
          Invocation.method(
            #createKey,
            [
              authorizations,
              name,
            ],
          ),
        )),
      ) as _i8.Future<_i4.CreateKeyResponse>);

  @override
  _i8.Future<void> deleteKey(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteKey,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i4.APIKeyWithAuthorizations>> listKeys(String? orgId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listKeys,
          [orgId],
        ),
        returnValue: _i8.Future<List<_i4.APIKeyWithAuthorizations>>.value(
            <_i4.APIKeyWithAuthorizations>[]),
      ) as _i8.Future<List<_i4.APIKeyWithAuthorizations>>);

  @override
  _i8.Future<_i4.RotateKeyResponse> rotateKey(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #rotateKey,
          [id],
        ),
        returnValue:
            _i8.Future<_i4.RotateKeyResponse>.value(_FakeRotateKeyResponse_23(
          this,
          Invocation.method(
            #rotateKey,
            [id],
          ),
        )),
      ) as _i8.Future<_i4.RotateKeyResponse>);

  @override
  _i8.Future<_i4.CreateKeyFromExistingKeyAuthorizationsResponse>
      createKeyFromExistingKeyAuthorizations(String? id) => (super.noSuchMethod(
            Invocation.method(
              #createKeyFromExistingKeyAuthorizations,
              [id],
            ),
            returnValue: _i8.Future<
                    _i4.CreateKeyFromExistingKeyAuthorizationsResponse>.value(
                _FakeCreateKeyFromExistingKeyAuthorizationsResponse_24(
              this,
              Invocation.method(
                #createKeyFromExistingKeyAuthorizations,
                [id],
              ),
            )),
          ) as _i8.Future<_i4.CreateKeyFromExistingKeyAuthorizationsResponse>);

  @override
  _i8.Future<_i4.GetOrganizationMetadataResponse> getOrganizationMetadata(
          String? organizationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrganizationMetadata,
          [organizationId],
        ),
        returnValue: _i8.Future<_i4.GetOrganizationMetadataResponse>.value(
            _FakeGetOrganizationMetadataResponse_25(
          this,
          Invocation.method(
            #getOrganizationMetadata,
            [organizationId],
          ),
        )),
      ) as _i8.Future<_i4.GetOrganizationMetadataResponse>);

  @override
  _i8.Future<void> updateOrganizationMetadata(
    String? organizationId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrganizationMetadata,
          [
            organizationId,
            data,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i4.GetLocationMetadataResponse> getLocationMetadata(
          String? locationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocationMetadata,
          [locationId],
        ),
        returnValue: _i8.Future<_i4.GetLocationMetadataResponse>.value(
            _FakeGetLocationMetadataResponse_26(
          this,
          Invocation.method(
            #getLocationMetadata,
            [locationId],
          ),
        )),
      ) as _i8.Future<_i4.GetLocationMetadataResponse>);

  @override
  _i8.Future<void> updateLocationMetadata(
    String? locationId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLocationMetadata,
          [
            locationId,
            data,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i4.GetRobotMetadataResponse> getRobotMetadata(String? robotId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotMetadata,
          [robotId],
        ),
        returnValue: _i8.Future<_i4.GetRobotMetadataResponse>.value(
            _FakeGetRobotMetadataResponse_27(
          this,
          Invocation.method(
            #getRobotMetadata,
            [robotId],
          ),
        )),
      ) as _i8.Future<_i4.GetRobotMetadataResponse>);

  @override
  _i8.Future<void> updateRobotMetadata(
    String? robotId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRobotMetadata,
          [
            robotId,
            data,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i4.GetRobotPartMetadataResponse> getRobotPartMetadata(
          String? robotPartId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotPartMetadata,
          [robotPartId],
        ),
        returnValue: _i8.Future<_i4.GetRobotPartMetadataResponse>.value(
            _FakeGetRobotPartMetadataResponse_28(
          this,
          Invocation.method(
            #getRobotPartMetadata,
            [robotPartId],
          ),
        )),
      ) as _i8.Future<_i4.GetRobotPartMetadataResponse>);

  @override
  _i8.Future<void> updateRobotPartMetadata(
    String? robotPartId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRobotPartMetadata,
          [
            robotPartId,
            data,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [PluginWifiConnectService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPluginWifiConnectService extends _i1.Mock
    implements _i3.PluginWifiConnectService {
  MockPluginWifiConnectService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<String?> getCurrentSSID() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentSSID,
          [],
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<bool> connectToSecureNetworkByPrefix({
    required String? prefix,
    required String? password,
    required bool? isWep,
    required bool? isWpa3,
    required bool? saveNetwork,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #connectToSecureNetworkByPrefix,
          [],
          {
            #prefix: prefix,
            #password: password,
            #isWep: isWep,
            #isWpa3: isWpa3,
            #saveNetwork: saveNetwork,
          },
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);
}

/// A class which mocks [PermissionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionService extends _i1.Mock implements _i3.PermissionService {
  MockPermissionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i9.PermissionStatus> requestLocationPermission() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestLocationPermission,
          [],
        ),
        returnValue:
            _i8.Future<_i9.PermissionStatus>.value(_i9.PermissionStatus.denied),
      ) as _i8.Future<_i9.PermissionStatus>);

  @override
  _i8.Future<bool> getLocationPermission() => (super.noSuchMethod(
        Invocation.method(
          #getLocationPermission,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);
}

/// A class which mocks [HotspotProvisioningFlowViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockHotspotProvisioningFlowViewModel extends _i1.Mock
    implements _i3.HotspotProvisioningFlowViewModel {
  MockHotspotProvisioningFlowViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Robot get robot => (super.noSuchMethod(
        Invocation.getter(#robot),
        returnValue: _FakeRobot_4(
          this,
          Invocation.getter(#robot),
        ),
      ) as _i4.Robot);

  @override
  _i2.Viam get viam => (super.noSuchMethod(
        Invocation.getter(#viam),
        returnValue: _FakeViam_0(
          this,
          Invocation.getter(#viam),
        ),
      ) as _i2.Viam);

  @override
  _i4.RobotPart get mainPart => (super.noSuchMethod(
        Invocation.getter(#mainPart),
        returnValue: _FakeRobotPart_16(
          this,
          Invocation.getter(#mainPart),
        ),
      ) as _i4.RobotPart);

  @override
  _i7.PageController get pageController => (super.noSuchMethod(
        Invocation.getter(#pageController),
        returnValue: _FakePageController_29(
          this,
          Invocation.getter(#pageController),
        ),
      ) as _i7.PageController);

  @override
  _i3.PluginWifiConnectService get pluginWifiConnectService =>
      (super.noSuchMethod(
        Invocation.getter(#pluginWifiConnectService),
        returnValue: _FakePluginWifiConnectService_1(
          this,
          Invocation.getter(#pluginWifiConnectService),
        ),
      ) as _i3.PluginWifiConnectService);

  @override
  _i3.PermissionService get permissionService => (super.noSuchMethod(
        Invocation.getter(#permissionService),
        returnValue: _FakePermissionService_2(
          this,
          Invocation.getter(#permissionService),
        ),
      ) as _i3.PermissionService);

  @override
  bool get overrideFragment => (super.noSuchMethod(
        Invocation.getter(#overrideFragment),
        returnValue: false,
      ) as bool);

  @override
  bool get replaceHardware => (super.noSuchMethod(
        Invocation.getter(#replaceHardware),
        returnValue: false,
      ) as bool);

  @override
  _i3.HotspotCredentialsInputViewModel get hotspotCredentialsInputViewModel =>
      (super.noSuchMethod(
        Invocation.getter(#hotspotCredentialsInputViewModel),
        returnValue: _FakeHotspotCredentialsInputViewModel_30(
          this,
          Invocation.getter(#hotspotCredentialsInputViewModel),
        ),
      ) as _i3.HotspotCredentialsInputViewModel);

  @override
  _i3.NetworkSelectionViewModel get networkSelectionViewModel =>
      (super.noSuchMethod(
        Invocation.getter(#networkSelectionViewModel),
        returnValue: _FakeNetworkSelectionViewModel_31(
          this,
          Invocation.getter(#networkSelectionViewModel),
        ),
      ) as _i3.NetworkSelectionViewModel);

  @override
  _i3.PasswordInputViewModel get passwordInputViewModel => (super.noSuchMethod(
        Invocation.getter(#passwordInputViewModel),
        returnValue: _FakePasswordInputViewModel_32(
          this,
          Invocation.getter(#passwordInputViewModel),
        ),
      ) as _i3.PasswordInputViewModel);

  @override
  _i3.ConfirmationViewModel get confirmationViewModel => (super.noSuchMethod(
        Invocation.getter(#confirmationViewModel),
        returnValue: _FakeConfirmationViewModel_33(
          this,
          Invocation.getter(#confirmationViewModel),
        ),
      ) as _i3.ConfirmationViewModel);

  @override
  String get hotspotPrefix => (super.noSuchMethod(
        Invocation.getter(#hotspotPrefix),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#hotspotPrefix),
        ),
      ) as String);

  @override
  String get hotspotPassword => (super.noSuchMethod(
        Invocation.getter(#hotspotPassword),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#hotspotPassword),
        ),
      ) as String);

  @override
  bool get isMissingRobotConfig => (super.noSuchMethod(
        Invocation.getter(#isMissingRobotConfig),
        returnValue: false,
      ) as bool);

  @override
  set hotspotCredentialsInputViewModel(
          _i3.HotspotCredentialsInputViewModel? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #hotspotCredentialsInputViewModel,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set networkSelectionViewModel(_i3.NetworkSelectionViewModel? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #networkSelectionViewModel,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set passwordInputViewModel(_i3.PasswordInputViewModel? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #passwordInputViewModel,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set confirmationViewModel(_i3.ConfirmationViewModel? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #confirmationViewModel,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set connectHotspotPrefixViewModel(_i3.ConnectHotspotPrefixViewModel? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #connectHotspotPrefixViewModel,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void onCredentialsSubmitted(
    String? prefix,
    String? password,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onCredentialsSubmitted,
          [
            prefix,
            password,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onPasswordSubmitted(String? fragmentId) => super.noSuchMethod(
        Invocation.method(
          #onPasswordSubmitted,
          [fragmentId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onNetworkSelected(_i2.NetworkInfo? network) => super.noSuchMethod(
        Invocation.method(
          #onNetworkSelected,
          [network],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> onPublicNetworkSelected(_i2.NetworkInfo? network) =>
      (super.noSuchMethod(
        Invocation.method(
          #onPublicNetworkSelected,
          [network],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void navigateToNextPage() => super.noSuchMethod(
        Invocation.method(
          #navigateToNextPage,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> resetConnectionState() => (super.noSuchMethod(
        Invocation.method(
          #resetConnectionState,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PageController].
///
/// See the documentation for Mockito's code generation for more information.
class MockPageController extends _i1.Mock implements _i7.PageController {
  MockPageController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get initialPage => (super.noSuchMethod(
        Invocation.getter(#initialPage),
        returnValue: 0,
      ) as int);

  @override
  bool get keepPage => (super.noSuchMethod(
        Invocation.getter(#keepPage),
        returnValue: false,
      ) as bool);

  @override
  double get viewportFraction => (super.noSuchMethod(
        Invocation.getter(#viewportFraction),
        returnValue: 0.0,
      ) as double);

  @override
  double get initialScrollOffset => (super.noSuchMethod(
        Invocation.getter(#initialScrollOffset),
        returnValue: 0.0,
      ) as double);

  @override
  bool get keepScrollOffset => (super.noSuchMethod(
        Invocation.getter(#keepScrollOffset),
        returnValue: false,
      ) as bool);

  @override
  Iterable<_i7.ScrollPosition> get positions => (super.noSuchMethod(
        Invocation.getter(#positions),
        returnValue: <_i7.ScrollPosition>[],
      ) as Iterable<_i7.ScrollPosition>);

  @override
  bool get hasClients => (super.noSuchMethod(
        Invocation.getter(#hasClients),
        returnValue: false,
      ) as bool);

  @override
  _i7.ScrollPosition get position => (super.noSuchMethod(
        Invocation.getter(#position),
        returnValue: _FakeScrollPosition_34(
          this,
          Invocation.getter(#position),
        ),
      ) as _i7.ScrollPosition);

  @override
  double get offset => (super.noSuchMethod(
        Invocation.getter(#offset),
        returnValue: 0.0,
      ) as double);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> animateToPage(
    int? page, {
    required Duration? duration,
    required _i7.Curve? curve,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #animateToPage,
          [page],
          {
            #duration: duration,
            #curve: curve,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void jumpToPage(int? page) => super.noSuchMethod(
        Invocation.method(
          #jumpToPage,
          [page],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> nextPage({
    required Duration? duration,
    required _i7.Curve? curve,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #nextPage,
          [],
          {
            #duration: duration,
            #curve: curve,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> previousPage({
    required Duration? duration,
    required _i7.Curve? curve,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #previousPage,
          [],
          {
            #duration: duration,
            #curve: curve,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i7.ScrollPosition createScrollPosition(
    _i7.ScrollPhysics? physics,
    _i7.ScrollContext? context,
    _i7.ScrollPosition? oldPosition,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createScrollPosition,
          [
            physics,
            context,
            oldPosition,
          ],
        ),
        returnValue: _FakeScrollPosition_34(
          this,
          Invocation.method(
            #createScrollPosition,
            [
              physics,
              context,
              oldPosition,
            ],
          ),
        ),
      ) as _i7.ScrollPosition);

  @override
  void attach(_i7.ScrollPosition? position) => super.noSuchMethod(
        Invocation.method(
          #attach,
          [position],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> animateTo(
    double? offset, {
    required Duration? duration,
    required _i7.Curve? curve,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #animateTo,
          [offset],
          {
            #duration: duration,
            #curve: curve,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void jumpTo(double? value) => super.noSuchMethod(
        Invocation.method(
          #jumpTo,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void detach(_i7.ScrollPosition? position) => super.noSuchMethod(
        Invocation.method(
          #detach,
          [position],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void debugFillDescription(List<String>? description) => super.noSuchMethod(
        Invocation.method(
          #debugFillDescription,
          [description],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [HotspotCredentialsInputViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockHotspotCredentialsInputViewModel extends _i1.Mock
    implements _i3.HotspotCredentialsInputViewModel {
  MockHotspotCredentialsInputViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  dynamic Function(
    String,
    String,
  ) get onCredentialsSubmitted => (super.noSuchMethod(
        Invocation.getter(#onCredentialsSubmitted),
        returnValue: (
          String prefix,
          String password,
        ) =>
            null,
      ) as dynamic Function(
        String,
        String,
      ));

  @override
  bool get isSubmitting => (super.noSuchMethod(
        Invocation.getter(#isSubmitting),
        returnValue: false,
      ) as bool);

  @override
  bool get hasConfiguredPrefix => (super.noSuchMethod(
        Invocation.getter(#hasConfiguredPrefix),
        returnValue: false,
      ) as bool);

  @override
  bool get hasConfiguredPassword => (super.noSuchMethod(
        Invocation.getter(#hasConfiguredPassword),
        returnValue: false,
      ) as bool);

  @override
  set isSubmitting(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isSubmitting,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void submitCredentials(
    String? prefix,
    String? password,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #submitCredentials,
          [
            prefix,
            password,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetSubmitting() => super.noSuchMethod(
        Invocation.method(
          #resetSubmitting,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [NetworkSelectionViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkSelectionViewModel extends _i1.Mock
    implements _i3.NetworkSelectionViewModel {
  MockNetworkSelectionViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.HotspotProvisioningRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeHotspotProvisioningRepository_35(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.HotspotProvisioningRepository);

  @override
  bool get loadingNetworks => (super.noSuchMethod(
        Invocation.getter(#loadingNetworks),
        returnValue: false,
      ) as bool);

  @override
  List<_i2.NetworkInfo> get machineVisibleNetworks => (super.noSuchMethod(
        Invocation.getter(#machineVisibleNetworks),
        returnValue: <_i2.NetworkInfo>[],
      ) as List<_i2.NetworkInfo>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i7.IconData signalToIcon(int? signal) => (super.noSuchMethod(
        Invocation.method(
          #signalToIcon,
          [signal],
        ),
        returnValue: _FakeIconData_36(
          this,
          Invocation.method(
            #signalToIcon,
            [signal],
          ),
        ),
      ) as _i7.IconData);

  @override
  _i7.IconData securityToIcon(String? security) => (super.noSuchMethod(
        Invocation.method(
          #securityToIcon,
          [security],
        ),
        returnValue: _FakeIconData_36(
          this,
          Invocation.method(
            #securityToIcon,
            [security],
          ),
        ),
      ) as _i7.IconData);

  @override
  _i8.Future<void> getNetworks({bool? refresh = false}) => (super.noSuchMethod(
        Invocation.method(
          #getNetworks,
          [],
          {#refresh: refresh},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void setLoadingNetworks(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setLoadingNetworks,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setMachineVisibleNetworks(List<_i2.NetworkInfo>? networks) =>
      super.noSuchMethod(
        Invocation.method(
          #setMachineVisibleNetworks,
          [networks],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PasswordInputViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockPasswordInputViewModel extends _i1.Mock
    implements _i3.PasswordInputViewModel {
  MockPasswordInputViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.TextEditingController get passwordController => (super.noSuchMethod(
        Invocation.getter(#passwordController),
        returnValue: _FakeTextEditingController_37(
          this,
          Invocation.getter(#passwordController),
        ),
      ) as _i7.TextEditingController);

  @override
  _i7.TextEditingController get ssidController => (super.noSuchMethod(
        Invocation.getter(#ssidController),
        returnValue: _FakeTextEditingController_37(
          this,
          Invocation.getter(#ssidController),
        ),
      ) as _i7.TextEditingController);

  @override
  bool get obscureText => (super.noSuchMethod(
        Invocation.getter(#obscureText),
        returnValue: false,
      ) as bool);

  @override
  bool get loading => (super.noSuchMethod(
        Invocation.getter(#loading),
        returnValue: false,
      ) as bool);

  @override
  _i4.RobotPart get mainPart => (super.noSuchMethod(
        Invocation.getter(#mainPart),
        returnValue: _FakeRobotPart_16(
          this,
          Invocation.getter(#mainPart),
        ),
      ) as _i4.RobotPart);

  @override
  dynamic Function(String?) get onPasswordSubmitted => (super.noSuchMethod(
        Invocation.getter(#onPasswordSubmitted),
        returnValue: (String? fragmentId) => null,
      ) as dynamic Function(String?));

  @override
  _i3.HotspotProvisioningRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeHotspotProvisioningRepository_35(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.HotspotProvisioningRepository);

  @override
  bool get areNetworkCredentialsValid => (super.noSuchMethod(
        Invocation.getter(#areNetworkCredentialsValid),
        returnValue: false,
      ) as bool);

  @override
  set network(_i2.NetworkInfo? value) => super.noSuchMethod(
        Invocation.setter(
          #network,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void toggleObscureText() => super.noSuchMethod(
        Invocation.method(
          #toggleObscureText,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearPassword() => super.noSuchMethod(
        Invocation.method(
          #clearPassword,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isPublicNetwork(_i2.NetworkInfo? network) => (super.noSuchMethod(
        Invocation.method(
          #isPublicNetwork,
          [network],
        ),
        returnValue: false,
      ) as bool);

  @override
  void setLoading(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setLoading,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> submitCredentials() => (super.noSuchMethod(
        Invocation.method(
          #submitCredentials,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ConfirmationViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfirmationViewModel extends _i1.Mock
    implements _i3.ConfirmationViewModel {
  MockConfirmationViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Stream<_i3.MachineStatus> get machineStatusStream => (super.noSuchMethod(
        Invocation.getter(#machineStatusStream),
        returnValue: _i8.Stream<_i3.MachineStatus>.empty(),
      ) as _i8.Stream<_i3.MachineStatus>);

  @override
  int get secondsLoading => (super.noSuchMethod(
        Invocation.getter(#secondsLoading),
        returnValue: 0,
      ) as int);

  @override
  _i4.Robot get robot => (super.noSuchMethod(
        Invocation.getter(#robot),
        returnValue: _FakeRobot_4(
          this,
          Invocation.getter(#robot),
        ),
      ) as _i4.Robot);

  @override
  bool get overrideFragment => (super.noSuchMethod(
        Invocation.getter(#overrideFragment),
        returnValue: false,
      ) as bool);

  @override
  bool get replaceHardware => (super.noSuchMethod(
        Invocation.getter(#replaceHardware),
        returnValue: false,
      ) as bool);

  @override
  set timer(_i8.Timer? value) => super.noSuchMethod(
        Invocation.setter(
          #timer,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void startCheckingOnline() => super.noSuchMethod(
        Invocation.method(
          #startCheckingOnline,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<bool> disconnectFromHotspot() => (super.noSuchMethod(
        Invocation.method(
          #disconnectFromHotspot,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> performFragmentOverride() => (super.noSuchMethod(
        Invocation.method(
          #performFragmentOverride,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> applyRobotConfig() => (super.noSuchMethod(
        Invocation.method(
          #applyRobotConfig,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addMachineStatus(_i3.MachineStatus? machineStatus) => super.noSuchMethod(
        Invocation.method(
          #addMachineStatus,
          [machineStatus],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void closeMachineStatusStream() => super.noSuchMethod(
        Invocation.method(
          #closeMachineStatusStream,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateFragmentId(String? fragmentId) => super.noSuchMethod(
        Invocation.method(
          #updateFragmentId,
          [fragmentId],
        ),
        returnValueForMissingStub: null,
      );
}
