// Mocks generated by Mockito 5.4.6 from annotations
// in viam_flutter_hotspot_provisioning_widget/test/mocks/generate_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:typed_data' as _i15;

import 'package:fixnum/fixnum.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:permission_handler/permission_handler.dart' as _i11;
import 'package:protobuf/protobuf.dart' as _i6;
import 'package:viam_flutter_hotspot_provisioning_widget/viam_flutter_hotspot_provisioning_widget.dart'
    as _i9;
import 'package:viam_sdk/protos/app/app.dart' as _i3;
import 'package:viam_sdk/protos/app/packages.dart' as _i14;
import 'package:viam_sdk/src/app/app.dart' as _i4;
import 'package:viam_sdk/src/app/billing.dart' as _i5;
import 'package:viam_sdk/src/gen/common/v1/common.pb.dart' as _i13;
import 'package:viam_sdk/src/gen/google/protobuf/timestamp.pb.dart' as _i8;
import 'package:viam_sdk/viam_sdk.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeViam_0 extends _i1.SmartFake implements _i2.Viam {
  _FakeViam_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetSmartMachineStatusResponse_1 extends _i1.SmartFake
    implements _i2.GetSmartMachineStatusResponse {
  _FakeGetSmartMachineStatusResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRobot_2 extends _i1.SmartFake implements _i3.Robot {
  _FakeRobot_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppClient_3 extends _i1.SmartFake implements _i4.AppClient {
  _FakeAppClient_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppRobotClient_4 extends _i1.SmartFake
    implements _i2.AppRobotClient {
  _FakeAppRobotClient_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBillingClient_5 extends _i1.SmartFake implements _i5.BillingClient {
  _FakeBillingClient_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDataClient_6 extends _i1.SmartFake implements _i2.DataClient {
  _FakeDataClient_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProvisioningClient_7 extends _i1.SmartFake
    implements _i2.ProvisioningClient {
  _FakeProvisioningClient_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRobotClient_8 extends _i1.SmartFake implements _i2.RobotClient {
  _FakeRobotClient_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrganization_9 extends _i1.SmartFake implements _i3.Organization {
  _FakeOrganization_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeListOrganizationMembersResponse_10 extends _i1.SmartFake
    implements _i3.ListOrganizationMembersResponse {
  _FakeListOrganizationMembersResponse_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrganizationInvite_11 extends _i1.SmartFake
    implements _i3.OrganizationInvite {
  _FakeOrganizationInvite_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocation_12 extends _i1.SmartFake implements _i3.Location {
  _FakeLocation_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocationAuth_13 extends _i1.SmartFake implements _i3.LocationAuth {
  _FakeLocationAuth_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRobotPart_14 extends _i1.SmartFake implements _i3.RobotPart {
  _FakeRobotPart_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetRobotPartLogsResponse_15 extends _i1.SmartFake
    implements _i3.GetRobotPartLogsResponse {
  _FakeGetRobotPartLogsResponse_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFragment_16 extends _i1.SmartFake implements _i3.Fragment {
  _FakeFragment_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRegistryItem_17 extends _i1.SmartFake implements _i3.RegistryItem {
  _FakeRegistryItem_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreateModuleResponse_18 extends _i1.SmartFake
    implements _i3.CreateModuleResponse {
  _FakeCreateModuleResponse_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeModule_19 extends _i1.SmartFake implements _i3.Module {
  _FakeModule_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreateKeyResponse_20 extends _i1.SmartFake
    implements _i3.CreateKeyResponse {
  _FakeCreateKeyResponse_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRotateKeyResponse_21 extends _i1.SmartFake
    implements _i3.RotateKeyResponse {
  _FakeRotateKeyResponse_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreateKeyFromExistingKeyAuthorizationsResponse_22 extends _i1
    .SmartFake implements _i3.CreateKeyFromExistingKeyAuthorizationsResponse {
  _FakeCreateKeyFromExistingKeyAuthorizationsResponse_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetOrganizationMetadataResponse_23 extends _i1.SmartFake
    implements _i3.GetOrganizationMetadataResponse {
  _FakeGetOrganizationMetadataResponse_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetLocationMetadataResponse_24 extends _i1.SmartFake
    implements _i3.GetLocationMetadataResponse {
  _FakeGetLocationMetadataResponse_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetRobotMetadataResponse_25 extends _i1.SmartFake
    implements _i3.GetRobotMetadataResponse {
  _FakeGetRobotMetadataResponse_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetRobotPartMetadataResponse_26 extends _i1.SmartFake
    implements _i3.GetRobotPartMetadataResponse {
  _FakeGetRobotPartMetadataResponse_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBuilderInfo_27 extends _i1.SmartFake implements _i6.BuilderInfo {
  _FakeBuilderInfo_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInt64_28 extends _i1.SmartFake implements _i7.Int64 {
  _FakeInt64_28(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUnknownFieldSet_29 extends _i1.SmartFake
    implements _i6.UnknownFieldSet {
  _FakeUnknownFieldSet_29(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTimestamp_30 extends _i1.SmartFake implements _i8.Timestamp {
  _FakeTimestamp_30(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGeneratedMessage_31 extends _i1.SmartFake
    implements _i6.GeneratedMessage {
  _FakeGeneratedMessage_31(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_32 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_32(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HotspotProvisioningRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHotspotProvisioningRepository extends _i1.Mock
    implements _i9.HotspotProvisioningRepository {
  MockHotspotProvisioningRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Viam get viam => (super.noSuchMethod(
        Invocation.getter(#viam),
        returnValue: _FakeViam_0(
          this,
          Invocation.getter(#viam),
        ),
      ) as _i2.Viam);

  @override
  _i10.Future<_i2.GetSmartMachineStatusResponse> getSmartMachineStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSmartMachineStatus,
          [],
        ),
        returnValue: _i10.Future<_i2.GetSmartMachineStatusResponse>.value(
            _FakeGetSmartMachineStatusResponse_1(
          this,
          Invocation.method(
            #getSmartMachineStatus,
            [],
          ),
        )),
      ) as _i10.Future<_i2.GetSmartMachineStatusResponse>);

  @override
  _i10.Future<void> setSmartMachineCredentials({
    required String? id,
    required String? secret,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSmartMachineCredentials,
          [],
          {
            #id: id,
            #secret: secret,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setNetworkCredentials({
    required _i2.NetworkType? type,
    required String? ssid,
    required String? psk,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNetworkCredentials,
          [],
          {
            #type: type,
            #ssid: ssid,
            #psk: psk,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> exitProvisioning() => (super.noSuchMethod(
        Invocation.method(
          #exitProvisioning,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i2.NetworkInfo>> getNetworkList() => (super.noSuchMethod(
        Invocation.method(
          #getNetworkList,
          [],
        ),
        returnValue:
            _i10.Future<List<_i2.NetworkInfo>>.value(<_i2.NetworkInfo>[]),
      ) as _i10.Future<List<_i2.NetworkInfo>>);

  @override
  _i10.Future<String?> getCurrentSSID() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentSSID,
          [],
        ),
        returnValue: _i10.Future<String?>.value(),
      ) as _i10.Future<String?>);

  @override
  _i10.Future<bool> connectToSecureNetworkByPrefix({
    required String? prefix,
    required String? password,
    required bool? isWep,
    required bool? isWpa3,
    required bool? saveNetwork,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #connectToSecureNetworkByPrefix,
          [],
          {
            #prefix: prefix,
            #password: password,
            #isWep: isWep,
            #isWpa3: isWpa3,
            #saveNetwork: saveNetwork,
          },
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<_i11.PermissionStatus> requestLocationPermission() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestLocationPermission,
          [],
        ),
        returnValue: _i10.Future<_i11.PermissionStatus>.value(
            _i11.PermissionStatus.denied),
      ) as _i10.Future<_i11.PermissionStatus>);

  @override
  _i10.Future<bool> getLocationPermission() => (super.noSuchMethod(
        Invocation.method(
          #getLocationPermission,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<void> updateRobotPart({
    required String? partId,
    required String? robotName,
    required Map<String, dynamic>? config,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRobotPart,
          [],
          {
            #partId: partId,
            #robotName: robotName,
            #config: config,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i3.Robot> getRobot(String? robotId) => (super.noSuchMethod(
        Invocation.method(
          #getRobot,
          [robotId],
        ),
        returnValue: _i10.Future<_i3.Robot>.value(_FakeRobot_2(
          this,
          Invocation.method(
            #getRobot,
            [robotId],
          ),
        )),
      ) as _i10.Future<_i3.Robot>);

  @override
  _i10.Future<_i9.MachineStatus> calculateMachineStatus(_i3.Robot? robot) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateMachineStatus,
          [robot],
        ),
        returnValue:
            _i10.Future<_i9.MachineStatus>.value(_i9.MachineStatus.online),
      ) as _i10.Future<_i9.MachineStatus>);
}

/// A class which mocks [Viam].
///
/// See the documentation for Mockito's code generation for more information.
class MockViam extends _i1.Mock implements _i2.Viam {
  MockViam() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.AppClient get appClient => (super.noSuchMethod(
        Invocation.getter(#appClient),
        returnValue: _FakeAppClient_3(
          this,
          Invocation.getter(#appClient),
        ),
      ) as _i4.AppClient);

  @override
  _i2.AppRobotClient get appRobotClient => (super.noSuchMethod(
        Invocation.getter(#appRobotClient),
        returnValue: _FakeAppRobotClient_4(
          this,
          Invocation.getter(#appRobotClient),
        ),
      ) as _i2.AppRobotClient);

  @override
  _i5.BillingClient get billingClient => (super.noSuchMethod(
        Invocation.getter(#billingClient),
        returnValue: _FakeBillingClient_5(
          this,
          Invocation.getter(#billingClient),
        ),
      ) as _i5.BillingClient);

  @override
  _i2.DataClient get dataClient => (super.noSuchMethod(
        Invocation.getter(#dataClient),
        returnValue: _FakeDataClient_6(
          this,
          Invocation.getter(#dataClient),
        ),
      ) as _i2.DataClient);

  @override
  _i2.ProvisioningClient get provisioningClient => (super.noSuchMethod(
        Invocation.getter(#provisioningClient),
        returnValue: _FakeProvisioningClient_7(
          this,
          Invocation.getter(#provisioningClient),
        ),
      ) as _i2.ProvisioningClient);

  @override
  _i10.Future<_i2.RobotClient> getRobotClient(_i3.Robot? robot) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotClient,
          [robot],
        ),
        returnValue: _i10.Future<_i2.RobotClient>.value(_FakeRobotClient_8(
          this,
          Invocation.method(
            #getRobotClient,
            [robot],
          ),
        )),
      ) as _i10.Future<_i2.RobotClient>);
}

/// A class which mocks [ProvisioningClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockProvisioningClient extends _i1.Mock
    implements _i2.ProvisioningClient {
  MockProvisioningClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i2.GetSmartMachineStatusResponse> getSmartMachineStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSmartMachineStatus,
          [],
        ),
        returnValue: _i10.Future<_i2.GetSmartMachineStatusResponse>.value(
            _FakeGetSmartMachineStatusResponse_1(
          this,
          Invocation.method(
            #getSmartMachineStatus,
            [],
          ),
        )),
      ) as _i10.Future<_i2.GetSmartMachineStatusResponse>);

  @override
  _i10.Future<void> setNetworkCredentials({
    _i2.NetworkType? type = _i2.NetworkType.wifi,
    String? ssid,
    String? psk,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNetworkCredentials,
          [],
          {
            #type: type,
            #ssid: ssid,
            #psk: psk,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setSmartMachineCredentials({
    required String? id,
    required String? secret,
    String? appAddress = 'https://app.viam.com:443',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSmartMachineCredentials,
          [],
          {
            #id: id,
            #secret: secret,
            #appAddress: appAddress,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<Iterable<_i2.NetworkInfo>> getNetworkList() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNetworkList,
          [],
        ),
        returnValue:
            _i10.Future<Iterable<_i2.NetworkInfo>>.value(<_i2.NetworkInfo>[]),
      ) as _i10.Future<Iterable<_i2.NetworkInfo>>);

  @override
  _i10.Future<void> exitProvisioning() => (super.noSuchMethod(
        Invocation.method(
          #exitProvisioning,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [AppClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppClient extends _i1.Mock implements _i4.AppClient {
  MockAppClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<_i3.LocationSummary>> listMachineSummaries(
          String? organizationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listMachineSummaries,
          [organizationId],
        ),
        returnValue: _i10.Future<List<_i3.LocationSummary>>.value(
            <_i3.LocationSummary>[]),
      ) as _i10.Future<List<_i3.LocationSummary>>);

  @override
  _i10.Future<String> getUserIdByEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #getUserIdByEmail,
          [email],
        ),
        returnValue: _i10.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #getUserIdByEmail,
            [email],
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<_i3.Organization> createOrganization(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrganization,
          [name],
        ),
        returnValue: _i10.Future<_i3.Organization>.value(_FakeOrganization_9(
          this,
          Invocation.method(
            #createOrganization,
            [name],
          ),
        )),
      ) as _i10.Future<_i3.Organization>);

  @override
  _i10.Future<List<_i3.Organization>> listOrganizations() =>
      (super.noSuchMethod(
        Invocation.method(
          #listOrganizations,
          [],
        ),
        returnValue:
            _i10.Future<List<_i3.Organization>>.value(<_i3.Organization>[]),
      ) as _i10.Future<List<_i3.Organization>>);

  @override
  _i10.Future<List<_i3.OrganizationIdentity>>
      getOrganizationsWithAccessToLocation(String? locationId) =>
          (super.noSuchMethod(
            Invocation.method(
              #getOrganizationsWithAccessToLocation,
              [locationId],
            ),
            returnValue: _i10.Future<List<_i3.OrganizationIdentity>>.value(
                <_i3.OrganizationIdentity>[]),
          ) as _i10.Future<List<_i3.OrganizationIdentity>>);

  @override
  _i10.Future<List<_i3.OrgDetails>> listOrganizationsByUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listOrganizationsByUser,
          [userId],
        ),
        returnValue:
            _i10.Future<List<_i3.OrgDetails>>.value(<_i3.OrgDetails>[]),
      ) as _i10.Future<List<_i3.OrgDetails>>);

  @override
  _i10.Future<_i3.Organization> getOrganization(String? organizationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrganization,
          [organizationId],
        ),
        returnValue: _i10.Future<_i3.Organization>.value(_FakeOrganization_9(
          this,
          Invocation.method(
            #getOrganization,
            [organizationId],
          ),
        )),
      ) as _i10.Future<_i3.Organization>);

  @override
  _i10.Future<bool> getOrganizationNamespaceAvailability(
          String? publicNamespace) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrganizationNamespaceAvailability,
          [publicNamespace],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<_i3.Organization> updateOrganization(
    String? organizationId, {
    String? name,
    String? publicNamespace,
    String? region,
    String? cid,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrganization,
          [organizationId],
          {
            #name: name,
            #publicNamespace: publicNamespace,
            #region: region,
            #cid: cid,
          },
        ),
        returnValue: _i10.Future<_i3.Organization>.value(_FakeOrganization_9(
          this,
          Invocation.method(
            #updateOrganization,
            [organizationId],
            {
              #name: name,
              #publicNamespace: publicNamespace,
              #region: region,
              #cid: cid,
            },
          ),
        )),
      ) as _i10.Future<_i3.Organization>);

  @override
  _i10.Future<void> deleteOrganization(String? organizationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOrganization,
          [organizationId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i3.ListOrganizationMembersResponse> listOrganizationMembers(
          String? organizationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listOrganizationMembers,
          [organizationId],
        ),
        returnValue: _i10.Future<_i3.ListOrganizationMembersResponse>.value(
            _FakeListOrganizationMembersResponse_10(
          this,
          Invocation.method(
            #listOrganizationMembers,
            [organizationId],
          ),
        )),
      ) as _i10.Future<_i3.ListOrganizationMembersResponse>);

  @override
  _i10.Future<_i3.OrganizationInvite> createOrganizationInvite(
    String? organizationId,
    String? email,
    List<_i2.ViamAuthorization>? authorizations, {
    bool? sendEmailInvite = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrganizationInvite,
          [
            organizationId,
            email,
            authorizations,
          ],
          {#sendEmailInvite: sendEmailInvite},
        ),
        returnValue: _i10.Future<_i3.OrganizationInvite>.value(
            _FakeOrganizationInvite_11(
          this,
          Invocation.method(
            #createOrganizationInvite,
            [
              organizationId,
              email,
              authorizations,
            ],
            {#sendEmailInvite: sendEmailInvite},
          ),
        )),
      ) as _i10.Future<_i3.OrganizationInvite>);

  @override
  _i10.Future<_i3.OrganizationInvite> updateOrganizationInviteAuthorizations(
    String? organizationId,
    String? email,
    List<_i2.ViamAuthorization>? addAuthorizations,
    List<_i2.ViamAuthorization>? removeAuthorizations,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrganizationInviteAuthorizations,
          [
            organizationId,
            email,
            addAuthorizations,
            removeAuthorizations,
          ],
        ),
        returnValue: _i10.Future<_i3.OrganizationInvite>.value(
            _FakeOrganizationInvite_11(
          this,
          Invocation.method(
            #updateOrganizationInviteAuthorizations,
            [
              organizationId,
              email,
              addAuthorizations,
              removeAuthorizations,
            ],
          ),
        )),
      ) as _i10.Future<_i3.OrganizationInvite>);

  @override
  _i10.Future<void> deleteOrganizationMember(
    String? organizationId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOrganizationMember,
          [
            organizationId,
            userId,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteOrganizationInvite(
    String? organizationId,
    String? email,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOrganizationInvite,
          [
            organizationId,
            email,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i3.OrganizationInvite> resendOrganizationInvite(
    String? organizationId,
    String? email, {
    bool? sendEmailInvite = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resendOrganizationInvite,
          [
            organizationId,
            email,
          ],
          {#sendEmailInvite: sendEmailInvite},
        ),
        returnValue: _i10.Future<_i3.OrganizationInvite>.value(
            _FakeOrganizationInvite_11(
          this,
          Invocation.method(
            #resendOrganizationInvite,
            [
              organizationId,
              email,
            ],
            {#sendEmailInvite: sendEmailInvite},
          ),
        )),
      ) as _i10.Future<_i3.OrganizationInvite>);

  @override
  _i10.Future<_i3.Location> createLocation(
    String? organizationId,
    String? name, {
    String? parentLocationId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLocation,
          [
            organizationId,
            name,
          ],
          {#parentLocationId: parentLocationId},
        ),
        returnValue: _i10.Future<_i3.Location>.value(_FakeLocation_12(
          this,
          Invocation.method(
            #createLocation,
            [
              organizationId,
              name,
            ],
            {#parentLocationId: parentLocationId},
          ),
        )),
      ) as _i10.Future<_i3.Location>);

  @override
  _i10.Future<_i3.Location> getLocation(String? locationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocation,
          [locationId],
        ),
        returnValue: _i10.Future<_i3.Location>.value(_FakeLocation_12(
          this,
          Invocation.method(
            #getLocation,
            [locationId],
          ),
        )),
      ) as _i10.Future<_i3.Location>);

  @override
  _i10.Future<_i3.Location> updateLocation(
    String? locationId, {
    String? name,
    String? parentLocationId,
    String? region,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLocation,
          [locationId],
          {
            #name: name,
            #parentLocationId: parentLocationId,
            #region: region,
          },
        ),
        returnValue: _i10.Future<_i3.Location>.value(_FakeLocation_12(
          this,
          Invocation.method(
            #updateLocation,
            [locationId],
            {
              #name: name,
              #parentLocationId: parentLocationId,
              #region: region,
            },
          ),
        )),
      ) as _i10.Future<_i3.Location>);

  @override
  _i10.Future<void> deleteLocation(String? locationId) => (super.noSuchMethod(
        Invocation.method(
          #deleteLocation,
          [locationId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i3.Location>> listLocations(String? organizationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listLocations,
          [organizationId],
        ),
        returnValue: _i10.Future<List<_i3.Location>>.value(<_i3.Location>[]),
      ) as _i10.Future<List<_i3.Location>>);

  @override
  _i10.Future<void> shareLocation(
    String? locationId,
    String? organizationId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #shareLocation,
          [
            locationId,
            organizationId,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> unshareLocation(
    String? locationId,
    String? organizationId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unshareLocation,
          [
            locationId,
            organizationId,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i3.LocationAuth> locationAuth(String? locationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #locationAuth,
          [locationId],
        ),
        returnValue: _i10.Future<_i3.LocationAuth>.value(_FakeLocationAuth_13(
          this,
          Invocation.method(
            #locationAuth,
            [locationId],
          ),
        )),
      ) as _i10.Future<_i3.LocationAuth>);

  @override
  _i10.Future<_i3.LocationAuth> createLocationSecret(String? locationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLocationSecret,
          [locationId],
        ),
        returnValue: _i10.Future<_i3.LocationAuth>.value(_FakeLocationAuth_13(
          this,
          Invocation.method(
            #createLocationSecret,
            [locationId],
          ),
        )),
      ) as _i10.Future<_i3.LocationAuth>);

  @override
  _i10.Future<void> deleteLocationSecret(
    String? locationId,
    String? secretId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLocationSecret,
          [
            locationId,
            secretId,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i3.Robot> getRobot(String? robotId) => (super.noSuchMethod(
        Invocation.method(
          #getRobot,
          [robotId],
        ),
        returnValue: _i10.Future<_i3.Robot>.value(_FakeRobot_2(
          this,
          Invocation.method(
            #getRobot,
            [robotId],
          ),
        )),
      ) as _i10.Future<_i3.Robot>);

  @override
  _i10.Future<List<_i3.RoverRentalRobot>> getRoverRentalRobots(String? orgId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRoverRentalRobots,
          [orgId],
        ),
        returnValue: _i10.Future<List<_i3.RoverRentalRobot>>.value(
            <_i3.RoverRentalRobot>[]),
      ) as _i10.Future<List<_i3.RoverRentalRobot>>);

  @override
  _i10.Future<List<_i3.RobotPart>> listRobotParts(String? robotId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listRobotParts,
          [robotId],
        ),
        returnValue: _i10.Future<List<_i3.RobotPart>>.value(<_i3.RobotPart>[]),
      ) as _i10.Future<List<_i3.RobotPart>>);

  @override
  _i10.Future<_i3.RobotPart> getRobotPart(String? partId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotPart,
          [partId],
        ),
        returnValue: _i10.Future<_i3.RobotPart>.value(_FakeRobotPart_14(
          this,
          Invocation.method(
            #getRobotPart,
            [partId],
          ),
        )),
      ) as _i10.Future<_i3.RobotPart>);

  @override
  _i10.Future<_i3.GetRobotPartLogsResponse> getLogs(
    String? partId, {
    String? filter,
    String? pageToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLogs,
          [partId],
          {
            #filter: filter,
            #pageToken: pageToken,
          },
        ),
        returnValue: _i10.Future<_i3.GetRobotPartLogsResponse>.value(
            _FakeGetRobotPartLogsResponse_15(
          this,
          Invocation.method(
            #getLogs,
            [partId],
            {
              #filter: filter,
              #pageToken: pageToken,
            },
          ),
        )),
      ) as _i10.Future<_i3.GetRobotPartLogsResponse>);

  @override
  _i10.Stream<List<_i13.LogEntry>> tailLogs(
    String? partId, {
    bool? errorsOnly = false,
    String? filter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #tailLogs,
          [partId],
          {
            #errorsOnly: errorsOnly,
            #filter: filter,
          },
        ),
        returnValue: _i10.Stream<List<_i13.LogEntry>>.empty(),
      ) as _i10.Stream<List<_i13.LogEntry>>);

  @override
  _i10.Future<List<_i3.RobotPartHistoryEntry>> getRobotPartHistory(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotPartHistory,
          [id],
        ),
        returnValue: _i10.Future<List<_i3.RobotPartHistoryEntry>>.value(
            <_i3.RobotPartHistoryEntry>[]),
      ) as _i10.Future<List<_i3.RobotPartHistoryEntry>>);

  @override
  _i10.Future<_i3.RobotPart> updateRobotPart(
    String? partId,
    String? name,
    Map<String, dynamic>? robotConfig, {
    DateTime? lastKnownUpdate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRobotPart,
          [
            partId,
            name,
            robotConfig,
          ],
          {#lastKnownUpdate: lastKnownUpdate},
        ),
        returnValue: _i10.Future<_i3.RobotPart>.value(_FakeRobotPart_14(
          this,
          Invocation.method(
            #updateRobotPart,
            [
              partId,
              name,
              robotConfig,
            ],
            {#lastKnownUpdate: lastKnownUpdate},
          ),
        )),
      ) as _i10.Future<_i3.RobotPart>);

  @override
  _i10.Future<String> newRobotPart(
    String? robotId,
    String? partName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #newRobotPart,
          [
            robotId,
            partName,
          ],
        ),
        returnValue: _i10.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #newRobotPart,
            [
              robotId,
              partName,
            ],
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<void> deleteRobotPart(String? partId) => (super.noSuchMethod(
        Invocation.method(
          #deleteRobotPart,
          [partId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i3.APIKeyWithAuthorizations>> getRobotApiKeys(
          String? robotId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotApiKeys,
          [robotId],
        ),
        returnValue: _i10.Future<List<_i3.APIKeyWithAuthorizations>>.value(
            <_i3.APIKeyWithAuthorizations>[]),
      ) as _i10.Future<List<_i3.APIKeyWithAuthorizations>>);

  @override
  _i10.Future<void> markPartAsMain(String? partId) => (super.noSuchMethod(
        Invocation.method(
          #markPartAsMain,
          [partId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> markPartForRestart(String? partId) => (super.noSuchMethod(
        Invocation.method(
          #markPartForRestart,
          [partId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i3.RobotPart> createRobotPartSecret(String? partId) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRobotPartSecret,
          [partId],
        ),
        returnValue: _i10.Future<_i3.RobotPart>.value(_FakeRobotPart_14(
          this,
          Invocation.method(
            #createRobotPartSecret,
            [partId],
          ),
        )),
      ) as _i10.Future<_i3.RobotPart>);

  @override
  _i10.Future<void> deleteRobotPartSecret(
    String? partId,
    String? secretId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRobotPartSecret,
          [
            partId,
            secretId,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i3.Robot>> listRobots(String? locationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listRobots,
          [locationId],
        ),
        returnValue: _i10.Future<List<_i3.Robot>>.value(<_i3.Robot>[]),
      ) as _i10.Future<List<_i3.Robot>>);

  @override
  _i10.Future<String> newMachine(
    String? name,
    String? locationId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #newMachine,
          [
            name,
            locationId,
          ],
        ),
        returnValue: _i10.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #newMachine,
            [
              name,
              locationId,
            ],
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<_i3.Robot> updateRobot(
    String? id,
    String? name,
    String? location,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRobot,
          [
            id,
            name,
            location,
          ],
        ),
        returnValue: _i10.Future<_i3.Robot>.value(_FakeRobot_2(
          this,
          Invocation.method(
            #updateRobot,
            [
              id,
              name,
              location,
            ],
          ),
        )),
      ) as _i10.Future<_i3.Robot>);

  @override
  _i10.Future<void> deleteRobot(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteRobot,
          [id],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i3.Fragment>> listFragments(
    String? organizationId,
    bool? showPublic, {
    List<_i3.FragmentVisibility>? fragmentVisibility,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listFragments,
          [
            organizationId,
            showPublic,
          ],
          {#fragmentVisibility: fragmentVisibility},
        ),
        returnValue: _i10.Future<List<_i3.Fragment>>.value(<_i3.Fragment>[]),
      ) as _i10.Future<List<_i3.Fragment>>);

  @override
  _i10.Future<_i3.Fragment> getFragment(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getFragment,
          [id],
        ),
        returnValue: _i10.Future<_i3.Fragment>.value(_FakeFragment_16(
          this,
          Invocation.method(
            #getFragment,
            [id],
          ),
        )),
      ) as _i10.Future<_i3.Fragment>);

  @override
  _i10.Future<_i3.Fragment> createFragment(
    String? name,
    Map<String, dynamic>? config,
    String? organizationId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFragment,
          [
            name,
            config,
            organizationId,
          ],
        ),
        returnValue: _i10.Future<_i3.Fragment>.value(_FakeFragment_16(
          this,
          Invocation.method(
            #createFragment,
            [
              name,
              config,
              organizationId,
            ],
          ),
        )),
      ) as _i10.Future<_i3.Fragment>);

  @override
  _i10.Future<_i3.Fragment> updateFragment(
    String? id,
    String? name,
    Map<String, dynamic>? config, {
    bool? public,
    _i3.FragmentVisibility? visibility,
    DateTime? lastKnownUpdate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFragment,
          [
            id,
            name,
            config,
          ],
          {
            #public: public,
            #visibility: visibility,
            #lastKnownUpdate: lastKnownUpdate,
          },
        ),
        returnValue: _i10.Future<_i3.Fragment>.value(_FakeFragment_16(
          this,
          Invocation.method(
            #updateFragment,
            [
              id,
              name,
              config,
            ],
            {
              #public: public,
              #visibility: visibility,
              #lastKnownUpdate: lastKnownUpdate,
            },
          ),
        )),
      ) as _i10.Future<_i3.Fragment>);

  @override
  _i10.Future<void> deleteFragment(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteFragment,
          [id],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> addRole(_i2.ViamAuthorization? authorization) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRole,
          [authorization],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> removeRole(_i2.ViamAuthorization? authorization) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeRole,
          [authorization],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> changeRole(
    _i2.ViamAuthorization? oldAuthorization,
    _i2.ViamAuthorization? newAuthorization,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeRole,
          [
            oldAuthorization,
            newAuthorization,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i3.Authorization>> listAuthorizations(
    String? organizationId, {
    List<String>? resourceIds = const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listAuthorizations,
          [organizationId],
          {#resourceIds: resourceIds},
        ),
        returnValue:
            _i10.Future<List<_i3.Authorization>>.value(<_i3.Authorization>[]),
      ) as _i10.Future<List<_i3.Authorization>>);

  @override
  _i10.Future<List<_i2.Permission>> checkPermissions(
    _i2.ResourceType? resourceType,
    String? resourceId,
    List<_i2.Permission>? permissions,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkPermissions,
          [
            resourceType,
            resourceId,
            permissions,
          ],
        ),
        returnValue:
            _i10.Future<List<_i2.Permission>>.value(<_i2.Permission>[]),
      ) as _i10.Future<List<_i2.Permission>>);

  @override
  _i10.Future<_i3.RegistryItem> getRegistryItem(String? itemId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRegistryItem,
          [itemId],
        ),
        returnValue: _i10.Future<_i3.RegistryItem>.value(_FakeRegistryItem_17(
          this,
          Invocation.method(
            #getRegistryItem,
            [itemId],
          ),
        )),
      ) as _i10.Future<_i3.RegistryItem>);

  @override
  _i10.Future<void> createRegistryItem(
    String? organizationId,
    String? name,
    _i14.PackageType? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRegistryItem,
          [
            organizationId,
            name,
            type,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateRegistryItem(
    String? itemId,
    _i14.PackageType? type,
    String? description,
    _i3.Visibility? visibility,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRegistryItem,
          [
            itemId,
            type,
            description,
            visibility,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i3.RegistryItem>> listRegistryItems(
    List<_i14.PackageType>? types,
    List<_i3.Visibility>? visibilities,
    List<String>? platforms,
    List<_i3.RegistryItemStatus>? statuses, {
    String? organizationId,
    String? searchTerm,
    String? pageToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listRegistryItems,
          [
            types,
            visibilities,
            platforms,
            statuses,
          ],
          {
            #organizationId: organizationId,
            #searchTerm: searchTerm,
            #pageToken: pageToken,
          },
        ),
        returnValue:
            _i10.Future<List<_i3.RegistryItem>>.value(<_i3.RegistryItem>[]),
      ) as _i10.Future<List<_i3.RegistryItem>>);

  @override
  _i10.Future<void> deleteRegistryItem(String? itemId) => (super.noSuchMethod(
        Invocation.method(
          #deleteRegistryItem,
          [itemId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i3.CreateModuleResponse> createModule(
    String? organizationId,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createModule,
          [
            organizationId,
            name,
          ],
        ),
        returnValue: _i10.Future<_i3.CreateModuleResponse>.value(
            _FakeCreateModuleResponse_18(
          this,
          Invocation.method(
            #createModule,
            [
              organizationId,
              name,
            ],
          ),
        )),
      ) as _i10.Future<_i3.CreateModuleResponse>);

  @override
  _i10.Future<String> updateModule(
    String? moduleId,
    _i3.Visibility? visibility,
    String? url,
    String? description,
    List<_i3.Model>? models,
    String? entrypoint,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateModule,
          [
            moduleId,
            visibility,
            url,
            description,
            models,
            entrypoint,
          ],
        ),
        returnValue: _i10.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #updateModule,
            [
              moduleId,
              visibility,
              url,
              description,
              models,
              entrypoint,
            ],
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<String> uploadModuleFile(
    _i3.ModuleFileInfo? moduleFileInfo,
    List<int>? file,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadModuleFile,
          [
            moduleFileInfo,
            file,
          ],
        ),
        returnValue: _i10.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #uploadModuleFile,
            [
              moduleFileInfo,
              file,
            ],
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<_i3.Module> getModule(String? moduleId) => (super.noSuchMethod(
        Invocation.method(
          #getModule,
          [moduleId],
        ),
        returnValue: _i10.Future<_i3.Module>.value(_FakeModule_19(
          this,
          Invocation.method(
            #getModule,
            [moduleId],
          ),
        )),
      ) as _i10.Future<_i3.Module>);

  @override
  _i10.Future<List<_i3.Module>> listModules(String? organizationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listModules,
          [organizationId],
        ),
        returnValue: _i10.Future<List<_i3.Module>>.value(<_i3.Module>[]),
      ) as _i10.Future<List<_i3.Module>>);

  @override
  _i10.Future<_i3.CreateKeyResponse> createKey(
    List<_i2.ViamAuthorization>? authorizations,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createKey,
          [
            authorizations,
            name,
          ],
        ),
        returnValue:
            _i10.Future<_i3.CreateKeyResponse>.value(_FakeCreateKeyResponse_20(
          this,
          Invocation.method(
            #createKey,
            [
              authorizations,
              name,
            ],
          ),
        )),
      ) as _i10.Future<_i3.CreateKeyResponse>);

  @override
  _i10.Future<void> deleteKey(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteKey,
          [id],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i3.APIKeyWithAuthorizations>> listKeys(String? orgId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listKeys,
          [orgId],
        ),
        returnValue: _i10.Future<List<_i3.APIKeyWithAuthorizations>>.value(
            <_i3.APIKeyWithAuthorizations>[]),
      ) as _i10.Future<List<_i3.APIKeyWithAuthorizations>>);

  @override
  _i10.Future<_i3.RotateKeyResponse> rotateKey(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #rotateKey,
          [id],
        ),
        returnValue:
            _i10.Future<_i3.RotateKeyResponse>.value(_FakeRotateKeyResponse_21(
          this,
          Invocation.method(
            #rotateKey,
            [id],
          ),
        )),
      ) as _i10.Future<_i3.RotateKeyResponse>);

  @override
  _i10.Future<_i3.CreateKeyFromExistingKeyAuthorizationsResponse>
      createKeyFromExistingKeyAuthorizations(String? id) => (super.noSuchMethod(
            Invocation.method(
              #createKeyFromExistingKeyAuthorizations,
              [id],
            ),
            returnValue: _i10.Future<
                    _i3.CreateKeyFromExistingKeyAuthorizationsResponse>.value(
                _FakeCreateKeyFromExistingKeyAuthorizationsResponse_22(
              this,
              Invocation.method(
                #createKeyFromExistingKeyAuthorizations,
                [id],
              ),
            )),
          ) as _i10.Future<_i3.CreateKeyFromExistingKeyAuthorizationsResponse>);

  @override
  _i10.Future<_i3.GetOrganizationMetadataResponse> getOrganizationMetadata(
          String? organizationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrganizationMetadata,
          [organizationId],
        ),
        returnValue: _i10.Future<_i3.GetOrganizationMetadataResponse>.value(
            _FakeGetOrganizationMetadataResponse_23(
          this,
          Invocation.method(
            #getOrganizationMetadata,
            [organizationId],
          ),
        )),
      ) as _i10.Future<_i3.GetOrganizationMetadataResponse>);

  @override
  _i10.Future<void> updateOrganizationMetadata(
    String? organizationId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrganizationMetadata,
          [
            organizationId,
            data,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i3.GetLocationMetadataResponse> getLocationMetadata(
          String? locationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocationMetadata,
          [locationId],
        ),
        returnValue: _i10.Future<_i3.GetLocationMetadataResponse>.value(
            _FakeGetLocationMetadataResponse_24(
          this,
          Invocation.method(
            #getLocationMetadata,
            [locationId],
          ),
        )),
      ) as _i10.Future<_i3.GetLocationMetadataResponse>);

  @override
  _i10.Future<void> updateLocationMetadata(
    String? locationId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLocationMetadata,
          [
            locationId,
            data,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i3.GetRobotMetadataResponse> getRobotMetadata(String? robotId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotMetadata,
          [robotId],
        ),
        returnValue: _i10.Future<_i3.GetRobotMetadataResponse>.value(
            _FakeGetRobotMetadataResponse_25(
          this,
          Invocation.method(
            #getRobotMetadata,
            [robotId],
          ),
        )),
      ) as _i10.Future<_i3.GetRobotMetadataResponse>);

  @override
  _i10.Future<void> updateRobotMetadata(
    String? robotId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRobotMetadata,
          [
            robotId,
            data,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i3.GetRobotPartMetadataResponse> getRobotPartMetadata(
          String? robotPartId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotPartMetadata,
          [robotPartId],
        ),
        returnValue: _i10.Future<_i3.GetRobotPartMetadataResponse>.value(
            _FakeGetRobotPartMetadataResponse_26(
          this,
          Invocation.method(
            #getRobotPartMetadata,
            [robotPartId],
          ),
        )),
      ) as _i10.Future<_i3.GetRobotPartMetadataResponse>);

  @override
  _i10.Future<void> updateRobotPartMetadata(
    String? robotPartId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRobotPartMetadata,
          [
            robotPartId,
            data,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [Timestamp].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimestamp extends _i1.Mock implements _i8.Timestamp {
  MockTimestamp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.BuilderInfo get info_ => (super.noSuchMethod(
        Invocation.getter(#info_),
        returnValue: _FakeBuilderInfo_27(
          this,
          Invocation.getter(#info_),
        ),
      ) as _i6.BuilderInfo);

  @override
  _i7.Int64 get seconds => (super.noSuchMethod(
        Invocation.getter(#seconds),
        returnValue: _FakeInt64_28(
          this,
          Invocation.getter(#seconds),
        ),
      ) as _i7.Int64);

  @override
  int get nanos => (super.noSuchMethod(
        Invocation.getter(#nanos),
        returnValue: 0,
      ) as int);

  @override
  set seconds(_i7.Int64? v) => super.noSuchMethod(
        Invocation.setter(
          #seconds,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set nanos(int? v) => super.noSuchMethod(
        Invocation.setter(
          #nanos,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.UnknownFieldSet get unknownFields => (super.noSuchMethod(
        Invocation.getter(#unknownFields),
        returnValue: _FakeUnknownFieldSet_29(
          this,
          Invocation.getter(#unknownFields),
        ),
      ) as _i6.UnknownFieldSet);

  @override
  bool get isFrozen => (super.noSuchMethod(
        Invocation.getter(#isFrozen),
        returnValue: false,
      ) as bool);

  @override
  _i8.Timestamp clone() => (super.noSuchMethod(
        Invocation.method(
          #clone,
          [],
        ),
        returnValue: _FakeTimestamp_30(
          this,
          Invocation.method(
            #clone,
            [],
          ),
        ),
      ) as _i8.Timestamp);

  @override
  _i8.Timestamp copyWith(void Function(_i8.Timestamp)? updates) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [updates],
        ),
        returnValue: _FakeTimestamp_30(
          this,
          Invocation.method(
            #copyWith,
            [updates],
          ),
        ),
      ) as _i8.Timestamp);

  @override
  _i8.Timestamp createEmptyInstance() => (super.noSuchMethod(
        Invocation.method(
          #createEmptyInstance,
          [],
        ),
        returnValue: _FakeTimestamp_30(
          this,
          Invocation.method(
            #createEmptyInstance,
            [],
          ),
        ),
      ) as _i8.Timestamp);

  @override
  bool hasSeconds() => (super.noSuchMethod(
        Invocation.method(
          #hasSeconds,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearSeconds() => super.noSuchMethod(
        Invocation.method(
          #clearSeconds,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool hasNanos() => (super.noSuchMethod(
        Invocation.method(
          #hasNanos,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearNanos() => super.noSuchMethod(
        Invocation.method(
          #clearNanos,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.GeneratedMessage freeze() => (super.noSuchMethod(
        Invocation.method(
          #freeze,
          [],
        ),
        returnValue: _FakeGeneratedMessage_31(
          this,
          Invocation.method(
            #freeze,
            [],
          ),
        ),
      ) as _i6.GeneratedMessage);

  @override
  _i6.GeneratedMessage toBuilder() => (super.noSuchMethod(
        Invocation.method(
          #toBuilder,
          [],
        ),
        returnValue: _FakeGeneratedMessage_31(
          this,
          Invocation.method(
            #toBuilder,
            [],
          ),
        ),
      ) as _i6.GeneratedMessage);

  @override
  bool hasRequiredFields() => (super.noSuchMethod(
        Invocation.method(
          #hasRequiredFields,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isInitialized() => (super.noSuchMethod(
        Invocation.method(
          #isInitialized,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int? getTagNumber(String? fieldName) => (super.noSuchMethod(Invocation.method(
        #getTagNumber,
        [fieldName],
      )) as int?);

  @override
  String toDebugString() => (super.noSuchMethod(
        Invocation.method(
          #toDebugString,
          [],
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #toDebugString,
            [],
          ),
        ),
      ) as String);

  @override
  void check() => super.noSuchMethod(
        Invocation.method(
          #check,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i15.Uint8List writeToBuffer() => (super.noSuchMethod(
        Invocation.method(
          #writeToBuffer,
          [],
        ),
        returnValue: _i15.Uint8List(0),
      ) as _i15.Uint8List);

  @override
  void writeToCodedBufferWriter(_i6.CodedBufferWriter? output) =>
      super.noSuchMethod(
        Invocation.method(
          #writeToCodedBufferWriter,
          [output],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void mergeFromCodedBufferReader(
    _i6.CodedBufferReader? input, [
    _i6.ExtensionRegistry? extensionRegistry = _i6.ExtensionRegistry.EMPTY,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #mergeFromCodedBufferReader,
          [
            input,
            extensionRegistry,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void mergeFromBuffer(
    List<int>? input, [
    _i6.ExtensionRegistry? extensionRegistry = _i6.ExtensionRegistry.EMPTY,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #mergeFromBuffer,
          [
            input,
            extensionRegistry,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> writeToJsonMap() => (super.noSuchMethod(
        Invocation.method(
          #writeToJsonMap,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  String writeToJson() => (super.noSuchMethod(
        Invocation.method(
          #writeToJson,
          [],
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #writeToJson,
            [],
          ),
        ),
      ) as String);

  @override
  Object? toProto3Json(
          {_i6.TypeRegistry? typeRegistry = const _i6.TypeRegistry.empty()}) =>
      (super.noSuchMethod(Invocation.method(
        #toProto3Json,
        [],
        {#typeRegistry: typeRegistry},
      )) as Object?);

  @override
  void mergeFromProto3Json(
    Object? json, {
    _i6.TypeRegistry? typeRegistry = const _i6.TypeRegistry.empty(),
    bool? ignoreUnknownFields = false,
    bool? supportNamesWithUnderscores = true,
    bool? permissiveEnums = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #mergeFromProto3Json,
          [json],
          {
            #typeRegistry: typeRegistry,
            #ignoreUnknownFields: ignoreUnknownFields,
            #supportNamesWithUnderscores: supportNamesWithUnderscores,
            #permissiveEnums: permissiveEnums,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void mergeFromJson(
    String? data, [
    _i6.ExtensionRegistry? extensionRegistry = _i6.ExtensionRegistry.EMPTY,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #mergeFromJson,
          [
            data,
            extensionRegistry,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void mergeFromJsonMap(
    Map<String, dynamic>? json, [
    _i6.ExtensionRegistry? extensionRegistry = _i6.ExtensionRegistry.EMPTY,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #mergeFromJsonMap,
          [
            json,
            extensionRegistry,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addExtension(
    _i6.Extension<dynamic>? extension,
    Object? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #addExtension,
          [
            extension,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearExtension(_i6.Extension<dynamic>? extension) => super.noSuchMethod(
        Invocation.method(
          #clearExtension,
          [extension],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearField(int? tagNumber) => super.noSuchMethod(
        Invocation.method(
          #clearField,
          [tagNumber],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int $_whichOneof(int? oneofIndex) => (super.noSuchMethod(
        Invocation.method(
          #$_whichOneof,
          [oneofIndex],
        ),
        returnValue: 0,
      ) as int);

  @override
  bool extensionsAreInitialized() => (super.noSuchMethod(
        Invocation.method(
          #extensionsAreInitialized,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  dynamic getExtension(_i6.Extension<dynamic>? extension) =>
      super.noSuchMethod(Invocation.method(
        #getExtension,
        [extension],
      ));

  @override
  dynamic getField(int? tagNumber) => super.noSuchMethod(Invocation.method(
        #getField,
        [tagNumber],
      ));

  @override
  List<T> createRepeatedField<T>(
    int? tagNumber,
    _i6.FieldInfo<T>? fi,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRepeatedField,
          [
            tagNumber,
            fi,
          ],
        ),
        returnValue: <T>[],
      ) as List<T>);

  @override
  Map<K, V> createMapField<K, V>(
    int? tagNumber,
    _i6.MapFieldInfo<K, V>? fi,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMapField,
          [
            tagNumber,
            fi,
          ],
        ),
        returnValue: <K, V>{},
      ) as Map<K, V>);

  @override
  dynamic getFieldOrNull(int? tagNumber) =>
      super.noSuchMethod(Invocation.method(
        #getFieldOrNull,
        [tagNumber],
      ));

  @override
  dynamic getDefaultForField(int? tagNumber) =>
      super.noSuchMethod(Invocation.method(
        #getDefaultForField,
        [tagNumber],
      ));

  @override
  bool hasExtension(_i6.Extension<dynamic>? extension) => (super.noSuchMethod(
        Invocation.method(
          #hasExtension,
          [extension],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool hasField(int? tagNumber) => (super.noSuchMethod(
        Invocation.method(
          #hasField,
          [tagNumber],
        ),
        returnValue: false,
      ) as bool);

  @override
  void mergeFromMessage(_i6.GeneratedMessage? other) => super.noSuchMethod(
        Invocation.method(
          #mergeFromMessage,
          [other],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void mergeUnknownFields(_i6.UnknownFieldSet? unknownFieldSet) =>
      super.noSuchMethod(
        Invocation.method(
          #mergeUnknownFields,
          [unknownFieldSet],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setExtension(
    _i6.Extension<dynamic>? extension,
    Object? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setExtension,
          [
            extension,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setField(
    int? tagNumber,
    Object? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setField,
          [
            tagNumber,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  T $_get<T>(
    int? index,
    T? defaultValue,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #$_get,
          [
            index,
            defaultValue,
          ],
        ),
        returnValue: _i12.dummyValue<T>(
          this,
          Invocation.method(
            #$_get,
            [
              index,
              defaultValue,
            ],
          ),
        ),
      ) as T);

  @override
  T $_getN<T>(int? index) => (super.noSuchMethod(
        Invocation.method(
          #$_getN,
          [index],
        ),
        returnValue: _i12.dummyValue<T>(
          this,
          Invocation.method(
            #$_getN,
            [index],
          ),
        ),
      ) as T);

  @override
  T $_ensure<T>(int? index) => (super.noSuchMethod(
        Invocation.method(
          #$_ensure,
          [index],
        ),
        returnValue: _i12.dummyValue<T>(
          this,
          Invocation.method(
            #$_ensure,
            [index],
          ),
        ),
      ) as T);

  @override
  List<T> $_getList<T>(int? index) => (super.noSuchMethod(
        Invocation.method(
          #$_getList,
          [index],
        ),
        returnValue: <T>[],
      ) as List<T>);

  @override
  Map<K, V> $_getMap<K, V>(int? index) => (super.noSuchMethod(
        Invocation.method(
          #$_getMap,
          [index],
        ),
        returnValue: <K, V>{},
      ) as Map<K, V>);

  @override
  bool $_getB(
    int? index,
    bool? defaultValue,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #$_getB,
          [
            index,
            defaultValue,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool $_getBF(int? index) => (super.noSuchMethod(
        Invocation.method(
          #$_getBF,
          [index],
        ),
        returnValue: false,
      ) as bool);

  @override
  int $_getI(
    int? index,
    int? defaultValue,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #$_getI,
          [
            index,
            defaultValue,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  int $_getIZ(int? index) => (super.noSuchMethod(
        Invocation.method(
          #$_getIZ,
          [index],
        ),
        returnValue: 0,
      ) as int);

  @override
  String $_getS(
    int? index,
    String? defaultValue,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #$_getS,
          [
            index,
            defaultValue,
          ],
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #$_getS,
            [
              index,
              defaultValue,
            ],
          ),
        ),
      ) as String);

  @override
  String $_getSZ(int? index) => (super.noSuchMethod(
        Invocation.method(
          #$_getSZ,
          [index],
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #$_getSZ,
            [index],
          ),
        ),
      ) as String);

  @override
  _i7.Int64 $_getI64(int? index) => (super.noSuchMethod(
        Invocation.method(
          #$_getI64,
          [index],
        ),
        returnValue: _FakeInt64_28(
          this,
          Invocation.method(
            #$_getI64,
            [index],
          ),
        ),
      ) as _i7.Int64);

  @override
  bool $_has(int? index) => (super.noSuchMethod(
        Invocation.method(
          #$_has,
          [index],
        ),
        returnValue: false,
      ) as bool);

  @override
  void $_setBool(
    int? index,
    bool? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #$_setBool,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $_setBytes(
    int? index,
    List<int>? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #$_setBytes,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $_setString(
    int? index,
    String? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #$_setString,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $_setFloat(
    int? index,
    double? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #$_setFloat,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $_setDouble(
    int? index,
    double? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #$_setDouble,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $_setSignedInt32(
    int? index,
    int? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #$_setSignedInt32,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $_setUnsignedInt32(
    int? index,
    int? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #$_setUnsignedInt32,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $_setInt64(
    int? index,
    _i7.Int64? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #$_setInt64,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  DateTime toDateTime({bool? toLocal = false}) => (super.noSuchMethod(
        Invocation.method(
          #toDateTime,
          [],
          {#toLocal: toLocal},
        ),
        returnValue: _FakeDateTime_32(
          this,
          Invocation.method(
            #toDateTime,
            [],
            {#toLocal: toLocal},
          ),
        ),
      ) as DateTime);
}
