name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: [ubuntu-large]
    container:
      image: ghcr.io/cirruslabs/flutter:${{ vars.FLUTTER_VERSION }}

    steps:
      - uses: actions/checkout@v6

      - run: flutter --version
      - run: flutter pub get

        # Verify formatting in all dart files
      - name: Verify formatting
        run: dart format --line-length=140 --set-exit-if-changed $(find ./lib -name "*.dart" -not -path "./lib/proto/*" -not -name "*.g.dart" -not -name "*.freezed.dart")

      - name: Analyze project source
        run: dart analyze $(find ./lib -name "*.dart" -not -path "./lib/proto/*" -not -name "*.g.dart" -not -name "*.freezed.dart")

      - name: Run tests
        run: flutter test